// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_dense_latency_ap_ufixed_8_1_4_0_0_ap_fixed_16_4_5_3_0_config5_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15
);

parameter    ap_ST_fsm_state1 = 22'd1;
parameter    ap_ST_fsm_state2 = 22'd2;
parameter    ap_ST_fsm_state3 = 22'd4;
parameter    ap_ST_fsm_state4 = 22'd8;
parameter    ap_ST_fsm_state5 = 22'd16;
parameter    ap_ST_fsm_state6 = 22'd32;
parameter    ap_ST_fsm_state7 = 22'd64;
parameter    ap_ST_fsm_state8 = 22'd128;
parameter    ap_ST_fsm_state9 = 22'd256;
parameter    ap_ST_fsm_state10 = 22'd512;
parameter    ap_ST_fsm_state11 = 22'd1024;
parameter    ap_ST_fsm_state12 = 22'd2048;
parameter    ap_ST_fsm_state13 = 22'd4096;
parameter    ap_ST_fsm_state14 = 22'd8192;
parameter    ap_ST_fsm_state15 = 22'd16384;
parameter    ap_ST_fsm_state16 = 22'd32768;
parameter    ap_ST_fsm_state17 = 22'd65536;
parameter    ap_ST_fsm_state18 = 22'd131072;
parameter    ap_ST_fsm_state19 = 22'd262144;
parameter    ap_ST_fsm_state20 = 22'd524288;
parameter    ap_ST_fsm_state21 = 22'd1048576;
parameter    ap_ST_fsm_state22 = 22'd2097152;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] p_read;
input  [7:0] p_read1;
input  [7:0] p_read2;
input  [7:0] p_read3;
input  [7:0] p_read4;
input  [7:0] p_read5;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;
output  [15:0] ap_return_8;
output  [15:0] ap_return_9;
output  [15:0] ap_return_10;
output  [15:0] ap_return_11;
output  [15:0] ap_return_12;
output  [15:0] ap_return_13;
output  [15:0] ap_return_14;
output  [15:0] ap_return_15;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [21:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [10:0] reg_591;
wire    ap_CS_fsm_state19;
reg   [10:0] reg_595;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state17;
reg   [11:0] reg_599;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state18;
reg   [11:0] reg_603;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state20;
wire    ap_CS_fsm_state21;
reg   [12:0] reg_607;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state16;
reg   [12:0] reg_611;
reg   [12:0] reg_615;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
reg   [12:0] reg_619;
reg   [7:0] p_read_20_reg_2769;
reg   [7:0] p_read_21_reg_2781;
wire   [13:0] zext_ln1171_13_fu_623_p1;
reg   [13:0] zext_ln1171_13_reg_2794;
reg   [5:0] lshr_ln717_2_reg_2799;
reg   [7:0] p_read_19_reg_2805;
wire    ap_CS_fsm_state2;
reg   [4:0] lshr_ln717_4_reg_2817;
reg   [10:0] trunc_ln712_4_reg_2822;
reg   [9:0] trunc_ln712_6_reg_2827;
reg   [7:0] p_read_18_reg_2832;
reg   [9:0] trunc_ln712_7_reg_2846;
wire   [14:0] zext_ln1171_37_fu_676_p1;
reg   [14:0] zext_ln1171_37_reg_2851;
reg   [10:0] trunc_ln717_61_reg_2858;
reg   [7:0] p_read_17_reg_2863;
wire    ap_CS_fsm_state5;
wire   [14:0] zext_ln1171_44_fu_680_p1;
reg   [14:0] zext_ln1171_44_reg_2873;
wire   [12:0] zext_ln1171_45_fu_685_p1;
reg   [12:0] zext_ln1171_45_reg_2878;
wire   [13:0] sub_ln1171_25_fu_702_p2;
reg   [13:0] sub_ln1171_25_reg_2883;
reg   [11:0] trunc_ln717_72_reg_2888;
reg   [9:0] trunc_ln712_9_reg_2893;
wire   [13:0] zext_ln1171_43_fu_718_p1;
reg   [13:0] zext_ln1171_43_reg_2898;
wire    ap_CS_fsm_state6;
reg   [11:0] trunc_ln717_67_reg_2903;
wire   [11:0] sub_ln1171_27_fu_752_p2;
reg   [11:0] sub_ln1171_27_reg_2908;
reg   [8:0] trunc_ln717_69_reg_2913;
reg   [10:0] trunc_ln717_74_reg_2918;
reg   [10:0] trunc_ln712_s_reg_2923;
reg   [7:0] p_read34_reg_2928;
wire   [13:0] zext_ln1171_3_fu_785_p1;
reg   [13:0] zext_ln1171_3_reg_2943;
reg   [10:0] lshr_ln717_s_reg_2948;
wire   [14:0] zext_ln1171_12_fu_790_p1;
reg   [14:0] zext_ln1171_12_reg_2953;
reg   [9:0] trunc_ln717_68_reg_2959;
wire   [10:0] add_ln740_23_fu_822_p2;
reg   [10:0] add_ln740_23_reg_2964;
wire   [12:0] add_ln740_56_fu_828_p2;
reg   [12:0] add_ln740_56_reg_2969;
wire   [11:0] add_ln740_57_fu_834_p2;
reg   [11:0] add_ln740_57_reg_2974;
reg   [11:0] trunc_ln717_34_reg_2979;
wire   [15:0] r_V_2_fu_843_p1;
reg   [15:0] r_V_2_reg_2984;
wire   [12:0] add_ln740_24_fu_859_p2;
reg   [12:0] add_ln740_24_reg_2989;
wire   [13:0] add_ln740_58_fu_871_p2;
reg   [13:0] add_ln740_58_reg_2994;
wire   [14:0] zext_ln1171_19_fu_877_p1;
reg   [14:0] zext_ln1171_19_reg_2999;
wire   [13:0] sub_ln1171_12_fu_892_p2;
reg   [13:0] sub_ln1171_12_reg_3005;
reg   [11:0] trunc_ln717_38_reg_3010;
reg   [11:0] trunc_ln717_45_reg_3015;
wire   [15:0] r_V_3_fu_916_p1;
reg   [15:0] r_V_3_reg_3020;
reg   [8:0] trunc_ln717_57_reg_3027;
reg   [8:0] trunc_ln717_60_reg_3032;
wire   [13:0] add_ln740_20_fu_987_p2;
reg   [13:0] add_ln740_20_reg_3037;
wire   [10:0] add_ln740_28_fu_993_p2;
reg   [10:0] add_ln740_28_reg_3042;
wire   [9:0] shl_ln717_6_fu_999_p3;
reg   [9:0] shl_ln717_6_reg_3047;
wire   [13:0] sub_ln1171_16_fu_1017_p2;
reg   [13:0] sub_ln1171_16_reg_3052;
reg   [10:0] lshr_ln717_3_reg_3057;
reg   [12:0] trunc_ln717_63_reg_3062;
wire   [13:0] add_ln740_29_fu_1098_p2;
reg   [13:0] add_ln740_29_reg_3067;
wire   [13:0] add_ln740_30_fu_1104_p2;
reg   [13:0] add_ln740_30_reg_3072;
wire   [10:0] add_ln740_62_fu_1110_p2;
reg   [10:0] add_ln740_62_reg_3077;
reg   [11:0] trunc_ln717_49_reg_3082;
reg   [12:0] trunc_ln717_53_reg_3087;
wire   [14:0] sub_ln1171_18_fu_1185_p2;
reg   [14:0] sub_ln1171_18_reg_3092;
wire   [15:0] r_V_5_fu_1191_p1;
reg   [15:0] r_V_5_reg_3097;
wire   [14:0] sub_ln1171_23_fu_1206_p2;
reg   [14:0] sub_ln1171_23_reg_3103;
wire   [11:0] add_ln740_33_fu_1227_p2;
reg   [11:0] add_ln740_33_reg_3108;
wire   [13:0] add_ln740_50_fu_1233_p2;
reg   [13:0] add_ln740_50_reg_3113;
wire   [13:0] add_ln740_63_fu_1248_p2;
reg   [13:0] add_ln740_63_reg_3118;
wire   [14:0] sub_ln1171_1_fu_1265_p2;
reg   [14:0] sub_ln1171_1_reg_3123;
reg   [12:0] trunc_ln717_29_reg_3128;
reg   [11:0] trunc_ln717_31_reg_3133;
reg   [12:0] trunc_ln717_33_reg_3138;
reg   [10:0] trunc_ln717_35_reg_3143;
reg   [12:0] trunc_ln717_39_reg_3148;
reg   [11:0] trunc_ln717_43_reg_3153;
reg   [12:0] trunc_ln717_55_reg_3158;
reg   [12:0] trunc_ln717_62_reg_3163;
reg   [12:0] trunc_ln717_66_reg_3168;
reg   [12:0] trunc_ln717_75_reg_3173;
reg   [9:0] trunc_ln712_1_reg_3178;
reg   [9:0] trunc_ln712_5_reg_3183;
wire   [13:0] add_ln740_34_fu_1608_p2;
reg   [13:0] add_ln740_34_reg_3188;
wire   [12:0] add_ln740_47_fu_1614_p2;
reg   [12:0] add_ln740_47_reg_3193;
wire   [12:0] add_ln740_48_fu_1620_p2;
reg   [12:0] add_ln740_48_reg_3198;
wire   [13:0] add_ln740_68_fu_1626_p2;
reg   [13:0] add_ln740_68_reg_3203;
reg   [9:0] lshr_ln_reg_3208;
reg   [12:0] trunc_ln717_s_reg_3213;
reg   [12:0] trunc_ln717_19_reg_3218;
reg   [9:0] trunc_ln717_20_reg_3223;
reg   [12:0] trunc_ln717_23_reg_3228;
reg   [6:0] trunc_ln717_24_reg_3233;
reg   [7:0] lshr_ln717_1_reg_3238;
reg   [8:0] trunc_ln717_42_reg_3243;
reg   [9:0] trunc_ln3_reg_3248;
wire  signed [13:0] sext_ln712_47_fu_1929_p1;
reg  signed [13:0] sext_ln712_47_reg_3253;
wire   [11:0] add_ln740_17_fu_1938_p2;
reg   [11:0] add_ln740_17_reg_3258;
wire   [10:0] add_ln740_18_fu_1944_p2;
reg   [10:0] add_ln740_18_reg_3263;
wire   [13:0] add_ln740_25_fu_1949_p2;
reg   [13:0] add_ln740_25_reg_3268;
wire   [13:0] add_ln740_35_fu_1955_p2;
reg   [13:0] add_ln740_35_reg_3274;
wire   [10:0] add_ln740_38_fu_1961_p2;
reg   [10:0] add_ln740_38_reg_3279;
wire   [10:0] add_ln740_43_fu_1967_p2;
reg   [10:0] add_ln740_43_reg_3284;
wire   [12:0] add_ln740_45_fu_1973_p2;
reg   [12:0] add_ln740_45_reg_3289;
wire   [13:0] add_ln740_49_fu_1985_p2;
reg   [13:0] add_ln740_49_reg_3294;
wire   [13:0] add_ln740_59_fu_1991_p2;
reg   [13:0] add_ln740_59_reg_3299;
wire   [13:0] add_ln740_64_fu_1997_p2;
reg   [13:0] add_ln740_64_reg_3304;
wire   [13:0] add_ln740_67_fu_2009_p2;
reg   [13:0] add_ln740_67_reg_3309;
wire   [12:0] add_ln740_72_fu_2015_p2;
reg   [12:0] add_ln740_72_reg_3314;
wire   [9:0] add_ln740_75_fu_2021_p2;
reg   [9:0] add_ln740_75_reg_3319;
wire   [13:0] add_ln740_79_fu_2033_p2;
reg   [13:0] add_ln740_79_reg_3324;
wire   [13:0] add_ln740_82_fu_2045_p2;
reg   [13:0] add_ln740_82_reg_3329;
wire   [13:0] sub_ln1171_21_fu_2062_p2;
reg   [13:0] sub_ln1171_21_reg_3334;
wire   [15:0] r_V_6_fu_2068_p1;
reg   [15:0] r_V_6_reg_3339;
wire   [12:0] add_ln740_15_fu_2118_p2;
reg   [12:0] add_ln740_15_reg_3344;
wire   [12:0] add_ln740_19_fu_2130_p2;
reg   [12:0] add_ln740_19_reg_3349;
wire   [13:0] add_ln740_3_fu_2141_p2;
reg   [13:0] add_ln740_3_reg_3354;
wire   [11:0] add_ln740_39_fu_2155_p2;
reg   [11:0] add_ln740_39_reg_3359;
wire   [12:0] add_ln740_44_fu_2174_p2;
reg   [12:0] add_ln740_44_reg_3364;
wire   [13:0] add_ln740_6_fu_2189_p2;
reg   [13:0] add_ln740_6_reg_3369;
wire   [10:0] add_ln740_53_fu_2194_p2;
reg   [10:0] add_ln740_53_reg_3374;
wire   [13:0] add_ln740_9_fu_2205_p2;
reg   [13:0] add_ln740_9_reg_3379;
wire   [13:0] add_ln740_10_fu_2215_p2;
reg   [13:0] add_ln740_10_reg_3384;
wire   [12:0] add_ln740_76_fu_2229_p2;
reg   [12:0] add_ln740_76_reg_3389;
reg   [11:0] trunc_ln717_64_reg_3394;
wire   [13:0] add_ln740_4_fu_2275_p2;
reg   [13:0] add_ln740_4_reg_3399;
wire   [13:0] add_ln740_40_fu_2281_p2;
reg   [13:0] add_ln740_40_reg_3404;
wire   [13:0] add_ln740_54_fu_2295_p2;
reg   [13:0] add_ln740_54_reg_3409;
reg   [12:0] trunc_ln_reg_3414;
wire   [13:0] add_ln740_7_fu_2349_p2;
reg   [13:0] add_ln740_7_reg_3419;
wire   [13:0] add_ln740_71_fu_2371_p2;
reg   [13:0] add_ln740_71_reg_3424;
reg   [5:0] trunc_ln717_27_reg_3429;
wire   [13:0] add_ln740_2_fu_2416_p2;
reg   [13:0] add_ln740_2_reg_3434;
wire   [13:0] add_ln740_8_fu_2426_p2;
reg   [13:0] add_ln740_8_reg_3439;
wire   [13:0] add_ln740_11_fu_2436_p2;
reg   [13:0] add_ln740_11_reg_3444;
wire   [15:0] r_V_1_fu_2441_p1;
reg   [15:0] r_V_1_reg_3449;
wire   [11:0] add_ln712_fu_2456_p2;
reg   [11:0] add_ln712_reg_3454;
wire   [13:0] add_ln740_1_fu_2470_p2;
reg   [13:0] add_ln740_1_reg_3459;
wire   [13:0] add_ln740_12_fu_2488_p2;
reg   [13:0] add_ln740_12_reg_3464;
wire  signed [13:0] sext_ln712_24_fu_2502_p1;
reg  signed [13:0] sext_ln712_24_reg_3469;
wire   [13:0] add_ln740_5_fu_2513_p2;
reg   [13:0] add_ln740_5_reg_3474;
wire   [13:0] add_ln740_13_fu_2525_p2;
reg   [13:0] add_ln740_13_reg_3479;
reg   [7:0] ap_port_reg_p_read;
reg   [7:0] ap_port_reg_p_read3;
reg   [7:0] ap_port_reg_p_read4;
reg   [7:0] ap_port_reg_p_read5;
reg   [7:0] grp_fu_256_p0;
wire   [13:0] zext_ln1171_27_fu_648_p1;
wire   [14:0] zext_ln1171_25_fu_663_p1;
wire   [13:0] zext_ln1171_35_fu_672_p1;
wire   [14:0] zext_ln1171_2_fu_2301_p1;
reg  signed [7:0] grp_fu_256_p1;
reg   [7:0] grp_fu_257_p0;
wire   [13:0] zext_ln1171_20_fu_628_p1;
wire   [12:0] zext_ln1171_26_fu_643_p1;
wire   [12:0] zext_ln1171_34_fu_667_p1;
wire   [15:0] r_V_0_fu_2377_p1;
reg  signed [8:0] grp_fu_257_p1;
wire   [13:0] grp_fu_521_p1;
wire   [15:0] grp_fu_256_p2;
wire   [13:0] grp_fu_531_p1;
wire   [15:0] grp_fu_257_p2;
wire   [12:0] grp_fu_541_p1;
wire   [14:0] grp_fu_551_p1;
wire   [14:0] grp_fu_561_p1;
wire   [12:0] shl_ln1171_18_fu_690_p3;
wire   [13:0] zext_ln1171_46_fu_698_p1;
wire   [12:0] trunc_ln712_9_fu_708_p1;
wire  signed [14:0] sext_ln1171_22_fu_723_p1;
wire   [14:0] sub_ln1171_26_fu_726_p2;
wire   [10:0] shl_ln1171_19_fu_741_p3;
wire   [11:0] zext_ln1171_47_fu_748_p1;
wire   [8:0] shl_ln1171_20_fu_758_p3;
wire   [11:0] zext_ln1171_48_fu_765_p1;
wire   [11:0] sub_ln1171_29_fu_769_p2;
wire  signed [12:0] sext_ln1171_23_fu_794_p1;
wire   [12:0] sub_ln1171_28_fu_797_p2;
wire   [10:0] zext_ln712_11_fu_816_p1;
wire  signed [12:0] sext_ln712_45_fu_812_p1;
wire  signed [12:0] sext_ln712_60_fu_819_p1;
wire  signed [12:0] sext_ln712_55_fu_847_p1;
wire   [12:0] zext_ln1171_38_fu_840_p1;
wire  signed [12:0] sext_ln740_5_fu_856_p1;
wire   [12:0] add_ln740_22_fu_850_p2;
wire  signed [13:0] sext_ln740_9_fu_868_p1;
wire  signed [13:0] sext_ln740_17_fu_865_p1;
wire   [12:0] shl_ln1171_s_fu_881_p3;
wire   [13:0] zext_ln1171_21_fu_888_p1;
wire  signed [14:0] sext_ln1171_17_fu_898_p1;
wire   [14:0] sub_ln1171_13_fu_901_p2;
wire   [10:0] shl_ln717_7_fu_923_p3;
wire   [8:0] shl_ln717_8_fu_934_p3;
wire   [11:0] zext_ln717_8_fu_930_p1;
wire   [11:0] zext_ln717_9_fu_941_p1;
wire   [11:0] sub_ln717_4_fu_945_p2;
wire   [11:0] zext_ln1171_36_fu_920_p1;
wire   [11:0] sub_ln1171_32_fu_961_p2;
wire  signed [13:0] sext_ln712_21_fu_977_p1;
wire  signed [13:0] sext_ln712_28_fu_980_p1;
wire   [10:0] zext_ln712_13_fu_984_p1;
wire   [12:0] shl_ln1171_11_fu_1006_p3;
wire   [13:0] zext_ln1171_28_fu_1013_p1;
wire   [13:0] zext_ln1171_30_fu_1023_p1;
wire   [13:0] add_ln1171_fu_1027_p2;
wire   [14:0] shl_ln1171_14_fu_1043_p3;
wire   [15:0] zext_ln1171_39_fu_1050_p1;
wire   [15:0] sub_ln1171_20_fu_1054_p2;
wire  signed [9:0] sext_ln712_48_fu_1082_p1;
wire  signed [13:0] sext_ln712_29_fu_1074_p1;
wire   [13:0] zext_ln712_12_fu_1085_p1;
wire  signed [13:0] sext_ln740_3_fu_1095_p1;
wire   [13:0] add_ln740_27_fu_1089_p2;
wire  signed [13:0] sext_ln712_22_fu_1070_p1;
wire  signed [13:0] sext_ln712_30_fu_1078_p1;
wire   [8:0] shl_ln1171_12_fu_1118_p3;
wire  signed [14:0] sext_ln1171_18_fu_1115_p1;
wire   [14:0] zext_ln1171_29_fu_1125_p1;
wire   [14:0] sub_ln1171_17_fu_1129_p2;
wire   [14:0] tmp_fu_1148_p3;
wire   [15:0] zext_ln1171_31_fu_1155_p1;
wire   [15:0] sub_ln1171_31_fu_1159_p2;
wire   [13:0] shl_ln1171_13_fu_1174_p3;
wire   [14:0] zext_ln1171_32_fu_1181_p1;
wire   [13:0] shl_ln1171_16_fu_1195_p3;
wire   [14:0] zext_ln1171_41_fu_1202_p1;
wire   [11:0] zext_ln712_3_fu_1212_p1;
wire  signed [13:0] sext_ln712_14_fu_1216_p1;
wire  signed [13:0] sext_ln712_32_fu_1220_p1;
wire  signed [13:0] sext_ln712_43_fu_1224_p1;
wire   [13:0] zext_ln717_7_fu_1145_p1;
wire   [13:0] zext_ln740_2_fu_1245_p1;
wire   [13:0] add_ln740_61_fu_1239_p2;
wire   [13:0] shl_ln1171_1_fu_1254_p3;
wire   [14:0] zext_ln1171_5_fu_1261_p1;
wire   [12:0] shl_ln717_2_fu_1274_p3;
wire   [12:0] zext_ln1171_11_fu_1271_p1;
wire   [14:0] shl_ln1171_6_fu_1287_p3;
wire   [15:0] zext_ln1171_14_fu_1294_p1;
wire   [15:0] sub_ln1171_8_fu_1298_p2;
wire   [13:0] shl_ln1171_7_fu_1314_p3;
wire   [11:0] shl_ln1171_8_fu_1325_p3;
wire   [14:0] zext_ln1171_16_fu_1332_p1;
wire   [14:0] zext_ln1171_15_fu_1321_p1;
wire   [14:0] sub_ln1171_9_fu_1336_p2;
wire   [15:0] zext_ln1171_17_fu_1352_p1;
wire   [15:0] sub_ln1171_10_fu_1360_p2;
wire   [13:0] zext_ln1171_18_fu_1356_p1;
wire   [13:0] sub_ln1171_11_fu_1376_p2;
wire   [14:0] shl_ln1171_2_fu_1392_p3;
wire   [15:0] zext_ln1171_22_fu_1399_p1;
wire   [15:0] sub_ln1171_14_fu_1403_p2;
wire   [13:0] shl_ln1171_9_fu_1419_p3;
wire   [8:0] shl_ln1171_10_fu_1430_p3;
wire   [14:0] zext_ln1171_24_fu_1437_p1;
wire   [14:0] zext_ln1171_23_fu_1426_p1;
wire   [14:0] sub_ln1171_15_fu_1441_p2;
wire   [11:0] shl_ln717_5_fu_1457_p3;
wire   [12:0] zext_ln717_5_fu_1464_p1;
wire   [12:0] zext_ln717_6_fu_1468_p1;
wire  signed [15:0] sext_ln1171_19_fu_1477_p1;
wire   [15:0] zext_ln1171_33_fu_1480_p1;
wire   [15:0] sub_ln1171_19_fu_1484_p2;
wire   [9:0] shl_ln1171_17_fu_1503_p3;
wire  signed [15:0] sext_ln1171_21_fu_1500_p1;
wire   [15:0] zext_ln1171_42_fu_1510_p1;
wire   [15:0] sub_ln1171_24_fu_1514_p2;
wire   [14:0] shl_ln1171_21_fu_1530_p3;
wire   [15:0] zext_ln1171_49_fu_1537_p1;
wire   [15:0] sub_ln1171_30_fu_1541_p2;
wire   [12:0] sub_ln717_1_fu_1281_p2;
wire   [12:0] sub_ln717_3_fu_1471_p2;
wire  signed [13:0] sext_ln712_39_fu_1586_p1;
wire  signed [13:0] sext_ln712_50_fu_1593_p1;
wire  signed [13:0] sext_ln740_4_fu_1605_p1;
wire   [13:0] add_ln740_32_fu_1599_p2;
wire  signed [12:0] sext_ln712_42_fu_1580_p1;
wire  signed [12:0] sext_ln712_49_fu_1590_p1;
wire  signed [12:0] sext_ln712_59_fu_1596_p1;
wire  signed [13:0] sext_ln712_17_fu_1567_p1;
wire  signed [13:0] sext_ln712_35_fu_1583_p1;
wire   [11:0] shl_ln_fu_1635_p3;
wire   [12:0] zext_ln717_fu_1642_p1;
wire   [12:0] zext_ln1171_fu_1632_p1;
wire   [12:0] add_ln717_fu_1646_p2;
wire  signed [15:0] sext_ln1171_fu_1662_p1;
wire   [15:0] zext_ln1171_6_fu_1665_p1;
wire   [15:0] sub_ln1171_2_fu_1669_p2;
wire   [10:0] shl_ln1171_3_fu_1685_p3;
wire   [15:0] zext_ln1171_7_fu_1692_p1;
wire   [15:0] sub_ln1171_3_fu_1696_p2;
wire   [12:0] shl_ln717_1_fu_1712_p3;
wire   [8:0] shl_ln1171_4_fu_1725_p3;
wire   [12:0] zext_ln1171_9_fu_1736_p1;
wire   [12:0] sub_ln1171_4_fu_1740_p2;
wire   [9:0] shl_ln1171_5_fu_1756_p3;
wire   [15:0] zext_ln1171_10_fu_1763_p1;
wire   [15:0] sub_ln1171_5_fu_1767_p2;
wire   [9:0] zext_ln1171_8_fu_1732_p1;
wire   [9:0] sub_ln1171_6_fu_1783_p2;
wire   [9:0] shl_ln717_3_fu_1802_p3;
wire   [10:0] zext_ln717_2_fu_1809_p1;
wire   [10:0] zext_ln717_1_fu_1799_p1;
wire   [10:0] add_ln717_1_fu_1813_p2;
wire   [10:0] shl_ln717_4_fu_1832_p3;
wire   [11:0] zext_ln717_4_fu_1839_p1;
wire   [11:0] zext_ln717_3_fu_1829_p1;
wire   [11:0] sub_ln717_2_fu_1843_p2;
wire   [12:0] sub_ln717_fu_1719_p2;
wire   [11:0] zext_ln712_2_fu_1869_p1;
wire   [11:0] zext_ln712_5_fu_1884_p1;
wire  signed [13:0] sext_ln712_15_fu_1875_p1;
wire  signed [13:0] sext_ln712_25_fu_1895_p1;
wire  signed [13:0] sext_ln712_23_fu_1888_p1;
wire  signed [13:0] sext_ln712_40_fu_1922_p1;
wire   [10:0] zext_ln712_8_fu_1905_p1;
wire   [10:0] zext_ln712_9_fu_1908_p1;
wire  signed [12:0] sext_ln712_13_fu_1872_p1;
wire  signed [12:0] sext_ln712_31_fu_1892_p1;
wire  signed [13:0] sext_ln740_16_fu_1982_p1;
wire  signed [13:0] sext_ln740_15_fu_1979_p1;
wire  signed [13:0] sext_ln712_26_fu_1898_p1;
wire  signed [13:0] sext_ln712_16_fu_1878_p1;
wire  signed [13:0] sext_ln712_34_fu_1911_p1;
wire  signed [13:0] sext_ln712_57_fu_1935_p1;
wire   [13:0] add_ln740_66_fu_2003_p2;
wire  signed [12:0] sext_ln712_18_fu_1881_p1;
wire  signed [12:0] sext_ln712_33_fu_1902_p1;
wire   [9:0] zext_ln712_14_fu_1932_p1;
wire  signed [13:0] sext_ln712_46_fu_1926_p1;
wire   [13:0] add_ln740_78_fu_2027_p2;
wire  signed [13:0] sext_ln712_36_fu_1915_p1;
wire   [13:0] add_ln740_81_fu_2039_p2;
wire  signed [13:0] sext_ln712_37_fu_1919_p1;
wire   [12:0] shl_ln1171_15_fu_2051_p3;
wire   [13:0] zext_ln1171_40_fu_2058_p1;
wire  signed [9:0] sext_ln712_27_fu_2094_p1;
wire  signed [12:0] sext_ln712_53_fu_2111_p1;
wire   [12:0] zext_ln712_fu_2073_p1;
wire  signed [12:0] sext_ln740_fu_2127_p1;
wire   [12:0] zext_ln740_fu_2124_p1;
wire  signed [13:0] sext_ln712_1_fu_2076_p1;
wire   [13:0] add_ln740_31_fu_2136_p2;
wire  signed [11:0] sext_ln712_58_fu_2114_p1;
wire   [11:0] zext_ln712_4_fu_2091_p1;
wire  signed [11:0] sext_ln740_12_fu_2152_p1;
wire   [11:0] add_ln740_37_fu_2146_p2;
wire   [10:0] zext_ln712_1_fu_2079_p1;
wire   [10:0] zext_ln712_6_fu_2097_p1;
wire   [10:0] add_ln740_42_fu_2161_p2;
wire  signed [12:0] sext_ln740_6_fu_2171_p1;
wire   [12:0] zext_ln740_1_fu_2167_p1;
wire  signed [13:0] sext_ln740_14_fu_2180_p1;
wire  signed [13:0] sext_ln712_3_fu_2082_p1;
wire   [13:0] add_ln740_46_fu_2183_p2;
wire   [10:0] zext_ln712_7_fu_2101_p1;
wire  signed [13:0] sext_ln712_6_fu_2085_p1;
wire   [13:0] add_ln740_60_fu_2200_p2;
wire  signed [13:0] sext_ln712_7_fu_2088_p1;
wire   [13:0] add_ln740_65_fu_2210_p2;
wire  signed [12:0] sext_ln712_51_fu_2107_p1;
wire   [12:0] zext_ln712_10_fu_2104_p1;
wire  signed [12:0] sext_ln740_19_fu_2226_p1;
wire   [12:0] add_ln740_74_fu_2220_p2;
wire  signed [14:0] sext_ln1171_20_fu_2235_p1;
wire   [14:0] sub_ln1171_22_fu_2238_p2;
wire  signed [13:0] sext_ln712_2_fu_2253_p1;
wire  signed [13:0] sext_ln740_13_fu_2272_p1;
wire   [13:0] add_ln740_36_fu_2267_p2;
wire  signed [13:0] sext_ln712_41_fu_2256_p1;
wire  signed [13:0] sext_ln712_52_fu_2259_p1;
wire  signed [13:0] sext_ln712_54_fu_2263_p1;
wire  signed [13:0] sext_ln740_8_fu_2292_p1;
wire   [13:0] add_ln740_52_fu_2287_p2;
wire   [14:0] shl_ln1_fu_2306_p3;
wire   [15:0] zext_ln1171_4_fu_2313_p1;
wire   [15:0] sub_ln1171_fu_2317_p2;
wire  signed [13:0] sext_ln712_4_fu_2333_p1;
wire   [13:0] add_ln740_51_fu_2344_p2;
wire  signed [13:0] sext_ln712_44_fu_2337_p1;
wire  signed [13:0] sext_ln712_56_fu_2340_p1;
wire   [10:0] or_ln_fu_2360_p3;
wire  signed [13:0] sext_ln740_10_fu_2367_p1;
wire   [13:0] add_ln740_70_fu_2354_p2;
wire   [8:0] zext_ln1171_1_fu_2381_p1;
wire   [8:0] sub_ln1171_7_fu_2384_p2;
wire  signed [13:0] sext_ln712_fu_2400_p1;
wire   [13:0] add_ln740_26_fu_2411_p2;
wire  signed [13:0] sext_ln712_5_fu_2403_p1;
wire   [13:0] add_ln740_55_fu_2421_p2;
wire  signed [13:0] sext_ln712_8_fu_2407_p1;
wire   [13:0] add_ln740_69_fu_2431_p2;
wire  signed [11:0] sext_ln712_10_fu_2449_p1;
wire  signed [13:0] sext_ln712_11_fu_2452_p1;
wire  signed [13:0] sext_ln740_11_fu_2467_p1;
wire   [13:0] add_ln740_21_fu_2462_p2;
wire  signed [13:0] sext_ln740_18_fu_2476_p1;
wire  signed [13:0] sext_ln712_9_fu_2445_p1;
wire  signed [13:0] sext_ln740_20_fu_2485_p1;
wire   [13:0] add_ln740_73_fu_2479_p2;
wire  signed [13:0] sext_ln712_12_fu_2494_p1;
wire  signed [13:0] sext_ln740_7_fu_2510_p1;
wire   [13:0] add_ln740_41_fu_2505_p2;
wire  signed [13:0] sext_ln712_19_fu_2498_p1;
wire   [13:0] add_ln740_77_fu_2519_p2;
wire    ap_CS_fsm_state22;
wire  signed [13:0] sext_ln740_2_fu_2538_p1;
wire  signed [13:0] sext_ln712_38_fu_2534_p1;
wire  signed [13:0] sext_ln740_1_fu_2547_p1;
wire   [13:0] add_ln740_16_fu_2541_p2;
wire   [13:0] add_ln740_fu_2550_p2;
wire  signed [13:0] sext_ln712_20_fu_2530_p1;
wire   [13:0] add_ln740_80_fu_2655_p2;
wire   [13:0] add_ln740_14_fu_2660_p2;
wire   [15:0] shl_ln2_fu_2556_p3;
wire   [15:0] shl_ln740_1_fu_2564_p3;
wire   [15:0] shl_ln740_2_fu_2571_p3;
wire   [15:0] shl_ln740_3_fu_2578_p3;
wire   [15:0] shl_ln740_4_fu_2585_p3;
wire   [15:0] shl_ln740_5_fu_2592_p3;
wire   [15:0] shl_ln740_6_fu_2599_p3;
wire   [15:0] shl_ln740_7_fu_2606_p3;
wire   [15:0] shl_ln740_8_fu_2613_p3;
wire   [15:0] shl_ln740_9_fu_2620_p3;
wire   [15:0] shl_ln740_s_fu_2627_p3;
wire   [15:0] shl_ln740_10_fu_2634_p3;
wire   [15:0] shl_ln740_11_fu_2641_p3;
wire   [15:0] shl_ln740_12_fu_2648_p3;
wire   [15:0] shl_ln740_13_fu_2665_p3;
reg   [21:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 22'd1;
end

myproject_mul_8ns_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8s_16_1_1_U26(
    .din0(grp_fu_256_p0),
    .din1(grp_fu_256_p1),
    .dout(grp_fu_256_p2)
);

myproject_mul_8ns_9s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 16 ))
mul_8ns_9s_16_1_1_U27(
    .din0(grp_fu_257_p0),
    .din1(grp_fu_257_p1),
    .dout(grp_fu_257_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        add_ln712_reg_3454 <= add_ln712_fu_2456_p2;
        add_ln740_12_reg_3464 <= add_ln740_12_fu_2488_p2;
        add_ln740_1_reg_3459 <= add_ln740_1_fu_2470_p2;
        r_V_1_reg_3449[7 : 0] <= r_V_1_fu_2441_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        add_ln740_10_reg_3384 <= add_ln740_10_fu_2215_p2;
        add_ln740_15_reg_3344 <= add_ln740_15_fu_2118_p2;
        add_ln740_19_reg_3349 <= add_ln740_19_fu_2130_p2;
        add_ln740_39_reg_3359 <= add_ln740_39_fu_2155_p2;
        add_ln740_3_reg_3354 <= add_ln740_3_fu_2141_p2;
        add_ln740_44_reg_3364 <= add_ln740_44_fu_2174_p2;
        add_ln740_53_reg_3374 <= add_ln740_53_fu_2194_p2;
        add_ln740_6_reg_3369 <= add_ln740_6_fu_2189_p2;
        add_ln740_76_reg_3389 <= add_ln740_76_fu_2229_p2;
        add_ln740_9_reg_3379 <= add_ln740_9_fu_2205_p2;
        r_V_6_reg_3339[7 : 0] <= r_V_6_fu_2068_p1[7 : 0];
        sub_ln1171_21_reg_3334[13 : 5] <= sub_ln1171_21_fu_2062_p2[13 : 5];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        add_ln740_11_reg_3444 <= add_ln740_11_fu_2436_p2;
        add_ln740_2_reg_3434 <= add_ln740_2_fu_2416_p2;
        add_ln740_8_reg_3439 <= add_ln740_8_fu_2426_p2;
        trunc_ln717_27_reg_3429 <= {{sub_ln1171_7_fu_2384_p2[8:3]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        add_ln740_13_reg_3479 <= add_ln740_13_fu_2525_p2;
        add_ln740_5_reg_3474 <= add_ln740_5_fu_2513_p2;
        sext_ln712_24_reg_3469 <= sext_ln712_24_fu_2502_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        add_ln740_17_reg_3258 <= add_ln740_17_fu_1938_p2;
        add_ln740_18_reg_3263 <= add_ln740_18_fu_1944_p2;
        add_ln740_25_reg_3268[13 : 4] <= add_ln740_25_fu_1949_p2[13 : 4];
        add_ln740_35_reg_3274 <= add_ln740_35_fu_1955_p2;
        add_ln740_38_reg_3279 <= add_ln740_38_fu_1961_p2;
        add_ln740_43_reg_3284 <= add_ln740_43_fu_1967_p2;
        add_ln740_45_reg_3289 <= add_ln740_45_fu_1973_p2;
        add_ln740_49_reg_3294 <= add_ln740_49_fu_1985_p2;
        add_ln740_59_reg_3299 <= add_ln740_59_fu_1991_p2;
        add_ln740_64_reg_3304 <= add_ln740_64_fu_1997_p2;
        add_ln740_67_reg_3309 <= add_ln740_67_fu_2009_p2;
        add_ln740_72_reg_3314 <= add_ln740_72_fu_2015_p2;
        add_ln740_75_reg_3319 <= add_ln740_75_fu_2021_p2;
        add_ln740_79_reg_3324 <= add_ln740_79_fu_2033_p2;
        add_ln740_82_reg_3329 <= add_ln740_82_fu_2045_p2;
        lshr_ln717_1_reg_3238 <= {{add_ln717_1_fu_1813_p2[10:3]}};
        lshr_ln_reg_3208 <= {{add_ln717_fu_1646_p2[12:3]}};
        sext_ln712_47_reg_3253 <= sext_ln712_47_fu_1929_p1;
        trunc_ln3_reg_3248 <= {{sub_ln717_fu_1719_p2[12:3]}};
        trunc_ln717_19_reg_3218 <= {{sub_ln1171_3_fu_1696_p2[15:3]}};
        trunc_ln717_20_reg_3223 <= {{sub_ln1171_4_fu_1740_p2[12:3]}};
        trunc_ln717_23_reg_3228 <= {{sub_ln1171_5_fu_1767_p2[15:3]}};
        trunc_ln717_24_reg_3233 <= {{sub_ln1171_6_fu_1783_p2[9:3]}};
        trunc_ln717_42_reg_3243 <= {{sub_ln717_2_fu_1843_p2[11:3]}};
        trunc_ln717_s_reg_3213 <= {{sub_ln1171_2_fu_1669_p2[15:3]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        add_ln740_20_reg_3037 <= add_ln740_20_fu_987_p2;
        add_ln740_28_reg_3042 <= add_ln740_28_fu_993_p2;
        trunc_ln717_57_reg_3027 <= {{sub_ln717_4_fu_945_p2[11:3]}};
        trunc_ln717_60_reg_3032 <= {{sub_ln1171_32_fu_961_p2[11:3]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        add_ln740_23_reg_2964 <= add_ln740_23_fu_822_p2;
        add_ln740_56_reg_2969 <= add_ln740_56_fu_828_p2;
        add_ln740_57_reg_2974 <= add_ln740_57_fu_834_p2;
        lshr_ln717_s_reg_2948 <= {{grp_fu_531_p1[13:3]}};
        p_read34_reg_2928 <= ap_port_reg_p_read;
        trunc_ln717_68_reg_2959 <= {{sub_ln1171_28_fu_797_p2[12:3]}};
        zext_ln1171_12_reg_2953[7 : 0] <= zext_ln1171_12_fu_790_p1[7 : 0];
        zext_ln1171_3_reg_2943[7 : 0] <= zext_ln1171_3_fu_785_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        add_ln740_24_reg_2989 <= add_ln740_24_fu_859_p2;
        add_ln740_58_reg_2994 <= add_ln740_58_fu_871_p2;
        r_V_2_reg_2984[7 : 0] <= r_V_2_fu_843_p1[7 : 0];
        trunc_ln717_34_reg_2979 <= {{grp_fu_551_p1[14:3]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        add_ln740_29_reg_3067 <= add_ln740_29_fu_1098_p2;
        add_ln740_30_reg_3072 <= add_ln740_30_fu_1104_p2;
        add_ln740_62_reg_3077 <= add_ln740_62_fu_1110_p2;
        lshr_ln717_3_reg_3057 <= {{add_ln1171_fu_1027_p2[13:3]}};
        shl_ln717_6_reg_3047[9 : 2] <= shl_ln717_6_fu_999_p3[9 : 2];
        sub_ln1171_16_reg_3052[13 : 5] <= sub_ln1171_16_fu_1017_p2[13 : 5];
        trunc_ln717_63_reg_3062 <= {{sub_ln1171_20_fu_1054_p2[15:3]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        add_ln740_33_reg_3108 <= add_ln740_33_fu_1227_p2;
        add_ln740_50_reg_3113 <= add_ln740_50_fu_1233_p2;
        add_ln740_63_reg_3118 <= add_ln740_63_fu_1248_p2;
        r_V_5_reg_3097[7 : 0] <= r_V_5_fu_1191_p1[7 : 0];
        sub_ln1171_18_reg_3092[14 : 6] <= sub_ln1171_18_fu_1185_p2[14 : 6];
        sub_ln1171_23_reg_3103[14 : 6] <= sub_ln1171_23_fu_1206_p2[14 : 6];
        trunc_ln717_49_reg_3082 <= {{sub_ln1171_17_fu_1129_p2[14:3]}};
        trunc_ln717_53_reg_3087 <= {{sub_ln1171_31_fu_1159_p2[15:3]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        add_ln740_34_reg_3188 <= add_ln740_34_fu_1608_p2;
        add_ln740_47_reg_3193 <= add_ln740_47_fu_1614_p2;
        add_ln740_48_reg_3198 <= add_ln740_48_fu_1620_p2;
        add_ln740_68_reg_3203 <= add_ln740_68_fu_1626_p2;
        sub_ln1171_1_reg_3123[14 : 6] <= sub_ln1171_1_fu_1265_p2[14 : 6];
        trunc_ln712_1_reg_3178 <= {{sub_ln717_1_fu_1281_p2[12:3]}};
        trunc_ln712_5_reg_3183 <= {{sub_ln717_3_fu_1471_p2[12:3]}};
        trunc_ln717_29_reg_3128 <= {{sub_ln1171_8_fu_1298_p2[15:3]}};
        trunc_ln717_31_reg_3133 <= {{sub_ln1171_9_fu_1336_p2[14:3]}};
        trunc_ln717_33_reg_3138 <= {{sub_ln1171_10_fu_1360_p2[15:3]}};
        trunc_ln717_35_reg_3143 <= {{sub_ln1171_11_fu_1376_p2[13:3]}};
        trunc_ln717_39_reg_3148 <= {{sub_ln1171_14_fu_1403_p2[15:3]}};
        trunc_ln717_43_reg_3153 <= {{sub_ln1171_15_fu_1441_p2[14:3]}};
        trunc_ln717_55_reg_3158 <= {{sub_ln1171_19_fu_1484_p2[15:3]}};
        trunc_ln717_62_reg_3163 <= {{grp_fu_257_p2[15:3]}};
        trunc_ln717_66_reg_3168 <= {{sub_ln1171_24_fu_1514_p2[15:3]}};
        trunc_ln717_75_reg_3173 <= {{sub_ln1171_30_fu_1541_p2[15:3]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        add_ln740_40_reg_3404 <= add_ln740_40_fu_2281_p2;
        add_ln740_4_reg_3399 <= add_ln740_4_fu_2275_p2;
        add_ln740_54_reg_3409 <= add_ln740_54_fu_2295_p2;
        trunc_ln717_64_reg_3394 <= {{sub_ln1171_22_fu_2238_p2[14:3]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        add_ln740_71_reg_3424 <= add_ln740_71_fu_2371_p2;
        add_ln740_7_reg_3419 <= add_ln740_7_fu_2349_p2;
        trunc_ln_reg_3414 <= {{sub_ln1171_fu_2317_p2[15:3]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_port_reg_p_read <= p_read;
        ap_port_reg_p_read3 <= p_read3;
        ap_port_reg_p_read4 <= p_read4;
        ap_port_reg_p_read5 <= p_read5;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        lshr_ln717_2_reg_2799 <= {{p_read2[7:2]}};
        p_read_20_reg_2769 <= p_read2;
        p_read_21_reg_2781 <= p_read1;
        zext_ln1171_13_reg_2794[7 : 0] <= zext_ln1171_13_fu_623_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        lshr_ln717_4_reg_2817 <= {{ap_port_reg_p_read3[7:3]}};
        p_read_19_reg_2805 <= ap_port_reg_p_read3;
        trunc_ln712_4_reg_2822 <= {{grp_fu_521_p1[13:3]}};
        trunc_ln712_6_reg_2827 <= {{grp_fu_541_p1[12:3]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        p_read_17_reg_2863 <= ap_port_reg_p_read5;
        sub_ln1171_25_reg_2883[13 : 5] <= sub_ln1171_25_fu_702_p2[13 : 5];
        trunc_ln712_9_reg_2893 <= {{trunc_ln712_9_fu_708_p1[12:3]}};
        trunc_ln717_72_reg_2888 <= {{grp_fu_561_p1[14:3]}};
        zext_ln1171_44_reg_2873[7 : 0] <= zext_ln1171_44_fu_680_p1[7 : 0];
        zext_ln1171_45_reg_2878[7 : 0] <= zext_ln1171_45_fu_685_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        p_read_18_reg_2832 <= ap_port_reg_p_read4;
        trunc_ln712_7_reg_2846 <= {{grp_fu_541_p1[12:3]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        r_V_3_reg_3020[7 : 0] <= r_V_3_fu_916_p1[7 : 0];
        trunc_ln717_38_reg_3010 <= {{sub_ln1171_13_fu_901_p2[14:3]}};
        trunc_ln717_45_reg_3015 <= {{grp_fu_561_p1[14:3]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state1))) begin
        reg_591 <= {{grp_fu_521_p1[13:3]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state15) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        reg_595 <= {{grp_fu_531_p1[13:3]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state18))) begin
        reg_599 <= {{grp_fu_551_p1[14:3]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state18))) begin
        reg_603 <= {{grp_fu_561_p1[14:3]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state8))) begin
        reg_607 <= {{grp_fu_257_p2[15:3]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state9))) begin
        reg_611 <= {{grp_fu_256_p2[15:3]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state12))) begin
        reg_615 <= {{grp_fu_256_p2[15:3]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state11))) begin
        reg_619 <= {{grp_fu_257_p2[15:3]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        sub_ln1171_12_reg_3005[13 : 5] <= sub_ln1171_12_fu_892_p2[13 : 5];
        zext_ln1171_19_reg_2999[7 : 0] <= zext_ln1171_19_fu_877_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        sub_ln1171_27_reg_2908[11 : 3] <= sub_ln1171_27_fu_752_p2[11 : 3];
        trunc_ln712_s_reg_2923 <= {{grp_fu_531_p1[13:3]}};
        trunc_ln717_67_reg_2903 <= {{sub_ln1171_26_fu_726_p2[14:3]}};
        trunc_ln717_69_reg_2913 <= {{sub_ln1171_29_fu_769_p2[11:3]}};
        trunc_ln717_74_reg_2918 <= {{grp_fu_521_p1[13:3]}};
        zext_ln1171_43_reg_2898[7 : 0] <= zext_ln1171_43_fu_718_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        trunc_ln717_61_reg_2858 <= {{grp_fu_521_p1[13:3]}};
        zext_ln1171_37_reg_2851[7 : 0] <= zext_ln1171_37_fu_676_p1[7 : 0];
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state22) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        grp_fu_256_p0 = r_V_1_reg_3449;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        grp_fu_256_p0 = r_V_1_fu_2441_p1;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        grp_fu_256_p0 = zext_ln1171_13_reg_2794;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_256_p0 = zext_ln1171_2_fu_2301_p1;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_256_p0 = r_V_6_reg_3339;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_256_p0 = r_V_6_fu_2068_p1;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_fu_256_p0 = zext_ln1171_37_reg_2851;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_fu_256_p0 = r_V_5_reg_3097;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_fu_256_p0 = r_V_5_fu_1191_p1;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state12))) begin
        grp_fu_256_p0 = r_V_3_reg_3020;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_256_p0 = r_V_3_fu_916_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_256_p0 = r_V_2_reg_2984;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_256_p0 = zext_ln1171_12_reg_2953;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_256_p0 = zext_ln1171_12_fu_790_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_256_p0 = zext_ln1171_43_fu_718_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_256_p0 = zext_ln1171_45_fu_685_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_256_p0 = zext_ln1171_35_fu_672_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_256_p0 = zext_ln1171_25_fu_663_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_256_p0 = zext_ln1171_27_fu_648_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_256_p0 = zext_ln1171_13_fu_623_p1;
    end else begin
        grp_fu_256_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        grp_fu_256_p1 = 16'd65435;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        grp_fu_256_p1 = 14'd16359;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_256_p1 = 15'd32733;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_256_p1 = 16'd65436;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_256_p1 = 16'd65419;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_fu_256_p1 = 15'd32729;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_fu_256_p1 = 16'd65445;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_fu_256_p1 = 16'd65428;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_256_p1 = 16'd65460;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state21))) begin
        grp_fu_256_p1 = 16'd65439;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_256_p1 = 16'd65434;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_256_p1 = 16'd65447;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_256_p1 = 15'd32714;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_256_p1 = 13'd29;
    end else if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4))) begin
        grp_fu_256_p1 = 14'd16363;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state8))) begin
        grp_fu_256_p1 = 15'd32709;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_256_p1 = 14'd38;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_256_p1 = 14'd45;
    end else begin
        grp_fu_256_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        grp_fu_257_p0 = zext_ln1171_37_reg_2851;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        grp_fu_257_p0 = zext_ln1171_12_reg_2953;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        grp_fu_257_p0 = r_V_0_fu_2377_p1;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_257_p0 = zext_ln1171_2_fu_2301_p1;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_257_p0 = zext_ln1171_3_reg_2943;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_257_p0 = r_V_6_fu_2068_p1;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_fu_257_p0 = zext_ln1171_43_reg_2898;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_fu_257_p0 = r_V_5_reg_3097;
    end else if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state12))) begin
        grp_fu_257_p0 = r_V_3_reg_3020;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_257_p0 = zext_ln1171_19_reg_2999;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_257_p0 = zext_ln1171_19_fu_877_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_257_p0 = r_V_2_fu_843_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_257_p0 = zext_ln1171_3_fu_785_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_257_p0 = zext_ln1171_43_fu_718_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_257_p0 = zext_ln1171_44_fu_680_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_257_p0 = zext_ln1171_37_fu_676_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_257_p0 = zext_ln1171_34_fu_667_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_257_p0 = zext_ln1171_26_fu_643_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_257_p0 = zext_ln1171_20_fu_628_p1;
    end else begin
        grp_fu_257_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        grp_fu_257_p1 = 15'd32731;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        grp_fu_257_p1 = 16'd65462;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_257_p1 = 15'd32730;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_257_p1 = 14'd16357;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_257_p1 = 16'd65469;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_fu_257_p1 = 14'd16362;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_fu_257_p1 = 16'd65465;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_fu_257_p1 = 16'd65457;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_257_p1 = 16'd65455;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_257_p1 = 16'd65444;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_257_p1 = 15'd32715;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state9))) begin
        grp_fu_257_p1 = 15'd32713;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_257_p1 = 16'd65426;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_257_p1 = 14'd52;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_257_p1 = 14'd39;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_257_p1 = 15'd32716;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_257_p1 = 15'd71;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_257_p1 = 13'd26;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_257_p1 = 13'd25;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_257_p1 = 14'd59;
    end else begin
        grp_fu_257_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1171_fu_1027_p2 = (zext_ln1171_28_fu_1013_p1 + zext_ln1171_30_fu_1023_p1);

assign add_ln712_fu_2456_p2 = ($signed(sext_ln712_10_fu_2449_p1) + $signed(12'd3072));

assign add_ln717_1_fu_1813_p2 = (zext_ln717_2_fu_1809_p1 + zext_ln717_1_fu_1799_p1);

assign add_ln717_fu_1646_p2 = (zext_ln717_fu_1642_p1 + zext_ln1171_fu_1632_p1);

assign add_ln740_10_fu_2215_p2 = (add_ln740_67_reg_3309 + add_ln740_65_fu_2210_p2);

assign add_ln740_11_fu_2436_p2 = (add_ln740_71_reg_3424 + add_ln740_69_fu_2431_p2);

assign add_ln740_12_fu_2488_p2 = ($signed(sext_ln740_20_fu_2485_p1) + $signed(add_ln740_73_fu_2479_p2));

assign add_ln740_13_fu_2525_p2 = (add_ln740_79_reg_3324 + add_ln740_77_fu_2519_p2);

assign add_ln740_14_fu_2660_p2 = (add_ln740_82_reg_3329 + add_ln740_80_fu_2655_p2);

assign add_ln740_15_fu_2118_p2 = ($signed(sext_ln712_53_fu_2111_p1) + $signed(zext_ln712_fu_2073_p1));

assign add_ln740_16_fu_2541_p2 = ($signed(sext_ln740_2_fu_2538_p1) + $signed(sext_ln712_38_fu_2534_p1));

assign add_ln740_17_fu_1938_p2 = (zext_ln712_2_fu_1869_p1 + zext_ln712_5_fu_1884_p1);

assign add_ln740_18_fu_1944_p2 = ($signed(trunc_ln712_4_reg_2822) + $signed(11'd1520));

assign add_ln740_19_fu_2130_p2 = ($signed(sext_ln740_fu_2127_p1) + $signed(zext_ln740_fu_2124_p1));

assign add_ln740_1_fu_2470_p2 = ($signed(sext_ln740_11_fu_2467_p1) + $signed(add_ln740_21_fu_2462_p2));

assign add_ln740_20_fu_987_p2 = ($signed(sext_ln712_21_fu_977_p1) + $signed(sext_ln712_28_fu_980_p1));

assign add_ln740_21_fu_2462_p2 = ($signed(add_ln740_20_reg_3037) + $signed(sext_ln712_11_fu_2452_p1));

assign add_ln740_22_fu_850_p2 = ($signed(sext_ln712_55_fu_847_p1) + $signed(zext_ln1171_38_fu_840_p1));

assign add_ln740_23_fu_822_p2 = ($signed(zext_ln712_11_fu_816_p1) + $signed(11'd1896));

assign add_ln740_24_fu_859_p2 = ($signed(sext_ln740_5_fu_856_p1) + $signed(add_ln740_22_fu_850_p2));

assign add_ln740_25_fu_1949_p2 = ($signed(sext_ln712_15_fu_1875_p1) + $signed(sext_ln712_25_fu_1895_p1));

assign add_ln740_26_fu_2411_p2 = ($signed(add_ln740_25_reg_3268) + $signed(sext_ln712_fu_2400_p1));

assign add_ln740_27_fu_1089_p2 = ($signed(sext_ln712_29_fu_1074_p1) + $signed(zext_ln712_12_fu_1085_p1));

assign add_ln740_28_fu_993_p2 = ($signed(zext_ln712_13_fu_984_p1) + $signed(11'd1936));

assign add_ln740_29_fu_1098_p2 = ($signed(sext_ln740_3_fu_1095_p1) + $signed(add_ln740_27_fu_1089_p2));

assign add_ln740_2_fu_2416_p2 = (add_ln740_29_reg_3067 + add_ln740_26_fu_2411_p2);

assign add_ln740_30_fu_1104_p2 = ($signed(sext_ln712_22_fu_1070_p1) + $signed(sext_ln712_30_fu_1078_p1));

assign add_ln740_31_fu_2136_p2 = ($signed(add_ln740_30_reg_3072) + $signed(sext_ln712_1_fu_2076_p1));

assign add_ln740_32_fu_1599_p2 = ($signed(sext_ln712_39_fu_1586_p1) + $signed(sext_ln712_50_fu_1593_p1));

assign add_ln740_33_fu_1227_p2 = ($signed(zext_ln712_3_fu_1212_p1) + $signed(12'd3984));

assign add_ln740_34_fu_1608_p2 = ($signed(sext_ln740_4_fu_1605_p1) + $signed(add_ln740_32_fu_1599_p2));

assign add_ln740_35_fu_1955_p2 = ($signed(sext_ln712_23_fu_1888_p1) + $signed(sext_ln712_40_fu_1922_p1));

assign add_ln740_36_fu_2267_p2 = ($signed(add_ln740_35_reg_3274) + $signed(sext_ln712_2_fu_2253_p1));

assign add_ln740_37_fu_2146_p2 = ($signed(sext_ln712_58_fu_2114_p1) + $signed(zext_ln712_4_fu_2091_p1));

assign add_ln740_38_fu_1961_p2 = ($signed(zext_ln712_8_fu_1905_p1) + $signed(11'd1640));

assign add_ln740_39_fu_2155_p2 = ($signed(sext_ln740_12_fu_2152_p1) + $signed(add_ln740_37_fu_2146_p2));

assign add_ln740_3_fu_2141_p2 = (add_ln740_34_reg_3188 + add_ln740_31_fu_2136_p2);

assign add_ln740_40_fu_2281_p2 = ($signed(sext_ln712_41_fu_2256_p1) + $signed(sext_ln712_52_fu_2259_p1));

assign add_ln740_41_fu_2505_p2 = ($signed(add_ln740_40_reg_3404) + $signed(sext_ln712_12_fu_2494_p1));

assign add_ln740_42_fu_2161_p2 = (zext_ln712_1_fu_2079_p1 + zext_ln712_6_fu_2097_p1);

assign add_ln740_43_fu_1967_p2 = ($signed(zext_ln712_9_fu_1908_p1) + $signed(11'd1488));

assign add_ln740_44_fu_2174_p2 = ($signed(sext_ln740_6_fu_2171_p1) + $signed(zext_ln740_1_fu_2167_p1));

assign add_ln740_45_fu_1973_p2 = ($signed(sext_ln712_13_fu_1872_p1) + $signed(sext_ln712_31_fu_1892_p1));

assign add_ln740_46_fu_2183_p2 = ($signed(sext_ln740_14_fu_2180_p1) + $signed(sext_ln712_3_fu_2082_p1));

assign add_ln740_47_fu_1614_p2 = ($signed(sext_ln712_42_fu_1580_p1) + $signed(sext_ln712_49_fu_1590_p1));

assign add_ln740_48_fu_1620_p2 = ($signed(sext_ln712_59_fu_1596_p1) + $signed(13'd7432));

assign add_ln740_49_fu_1985_p2 = ($signed(sext_ln740_16_fu_1982_p1) + $signed(sext_ln740_15_fu_1979_p1));

assign add_ln740_4_fu_2275_p2 = ($signed(sext_ln740_13_fu_2272_p1) + $signed(add_ln740_36_fu_2267_p2));

assign add_ln740_50_fu_1233_p2 = ($signed(sext_ln712_14_fu_1216_p1) + $signed(sext_ln712_32_fu_1220_p1));

assign add_ln740_51_fu_2344_p2 = ($signed(add_ln740_50_reg_3113) + $signed(sext_ln712_4_fu_2333_p1));

assign add_ln740_52_fu_2287_p2 = ($signed(sext_ln712_47_reg_3253) + $signed(sext_ln712_54_fu_2263_p1));

assign add_ln740_53_fu_2194_p2 = ($signed(zext_ln712_7_fu_2101_p1) + $signed(11'd1064));

assign add_ln740_54_fu_2295_p2 = ($signed(sext_ln740_8_fu_2292_p1) + $signed(add_ln740_52_fu_2287_p2));

assign add_ln740_55_fu_2421_p2 = ($signed(add_ln740_25_reg_3268) + $signed(sext_ln712_5_fu_2403_p1));

assign add_ln740_56_fu_828_p2 = ($signed(sext_ln712_45_fu_812_p1) + $signed(sext_ln712_60_fu_819_p1));

assign add_ln740_57_fu_834_p2 = ($signed(reg_603) + $signed(12'd3752));

assign add_ln740_58_fu_871_p2 = ($signed(sext_ln740_9_fu_868_p1) + $signed(sext_ln740_17_fu_865_p1));

assign add_ln740_59_fu_1991_p2 = ($signed(sext_ln712_15_fu_1875_p1) + $signed(sext_ln712_26_fu_1898_p1));

assign add_ln740_5_fu_2513_p2 = ($signed(sext_ln740_7_fu_2510_p1) + $signed(add_ln740_41_fu_2505_p2));

assign add_ln740_60_fu_2200_p2 = ($signed(add_ln740_59_reg_3299) + $signed(sext_ln712_6_fu_2085_p1));

assign add_ln740_61_fu_1239_p2 = ($signed(sext_ln712_43_fu_1224_p1) + $signed(zext_ln717_7_fu_1145_p1));

assign add_ln740_62_fu_1110_p2 = (trunc_ln712_s_reg_2923 + 11'd192);

assign add_ln740_63_fu_1248_p2 = (zext_ln740_2_fu_1245_p1 + add_ln740_61_fu_1239_p2);

assign add_ln740_64_fu_1997_p2 = ($signed(sext_ln712_16_fu_1878_p1) + $signed(sext_ln712_34_fu_1911_p1));

assign add_ln740_65_fu_2210_p2 = ($signed(add_ln740_64_reg_3304) + $signed(sext_ln712_7_fu_2088_p1));

assign add_ln740_66_fu_2003_p2 = ($signed(sext_ln712_57_fu_1935_p1) + $signed(14'd15360));

assign add_ln740_67_fu_2009_p2 = ($signed(add_ln740_66_fu_2003_p2) + $signed(sext_ln712_47_fu_1929_p1));

assign add_ln740_68_fu_1626_p2 = ($signed(sext_ln712_17_fu_1567_p1) + $signed(sext_ln712_35_fu_1583_p1));

assign add_ln740_69_fu_2431_p2 = ($signed(add_ln740_68_reg_3203) + $signed(sext_ln712_8_fu_2407_p1));

assign add_ln740_6_fu_2189_p2 = (add_ln740_49_reg_3294 + add_ln740_46_fu_2183_p2);

assign add_ln740_70_fu_2354_p2 = ($signed(sext_ln712_44_fu_2337_p1) + $signed(sext_ln712_56_fu_2340_p1));

assign add_ln740_71_fu_2371_p2 = ($signed(sext_ln740_10_fu_2367_p1) + $signed(add_ln740_70_fu_2354_p2));

assign add_ln740_72_fu_2015_p2 = ($signed(sext_ln712_18_fu_1881_p1) + $signed(sext_ln712_33_fu_1902_p1));

assign add_ln740_73_fu_2479_p2 = ($signed(sext_ln740_18_fu_2476_p1) + $signed(sext_ln712_9_fu_2445_p1));

assign add_ln740_74_fu_2220_p2 = ($signed(sext_ln712_51_fu_2107_p1) + $signed(zext_ln712_10_fu_2104_p1));

assign add_ln740_75_fu_2021_p2 = ($signed(zext_ln712_14_fu_1932_p1) + $signed(10'd640));

assign add_ln740_76_fu_2229_p2 = ($signed(sext_ln740_19_fu_2226_p1) + $signed(add_ln740_74_fu_2220_p2));

assign add_ln740_77_fu_2519_p2 = ($signed(sext_ln712_24_fu_2502_p1) + $signed(sext_ln712_19_fu_2498_p1));

assign add_ln740_78_fu_2027_p2 = ($signed(sext_ln712_46_fu_1926_p1) + $signed(sext_ln712_57_fu_1935_p1));

assign add_ln740_79_fu_2033_p2 = ($signed(add_ln740_78_fu_2027_p2) + $signed(sext_ln712_36_fu_1915_p1));

assign add_ln740_7_fu_2349_p2 = (add_ln740_54_reg_3409 + add_ln740_51_fu_2344_p2);

assign add_ln740_80_fu_2655_p2 = ($signed(sext_ln712_24_reg_3469) + $signed(sext_ln712_20_fu_2530_p1));

assign add_ln740_81_fu_2039_p2 = ($signed(sext_ln712_47_fu_1929_p1) + $signed(sext_ln712_57_fu_1935_p1));

assign add_ln740_82_fu_2045_p2 = ($signed(add_ln740_81_fu_2039_p2) + $signed(sext_ln712_37_fu_1919_p1));

assign add_ln740_8_fu_2426_p2 = (add_ln740_58_reg_2994 + add_ln740_55_fu_2421_p2);

assign add_ln740_9_fu_2205_p2 = (add_ln740_63_reg_3118 + add_ln740_60_fu_2200_p2);

assign add_ln740_fu_2550_p2 = ($signed(sext_ln740_1_fu_2547_p1) + $signed(add_ln740_16_fu_2541_p2));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_return_0 = shl_ln2_fu_2556_p3;

assign ap_return_1 = shl_ln740_1_fu_2564_p3;

assign ap_return_10 = shl_ln740_s_fu_2627_p3;

assign ap_return_11 = shl_ln740_10_fu_2634_p3;

assign ap_return_12 = shl_ln740_11_fu_2641_p3;

assign ap_return_13 = shl_ln740_12_fu_2648_p3;

assign ap_return_14 = shl_ln740_s_fu_2627_p3;

assign ap_return_15 = shl_ln740_13_fu_2665_p3;

assign ap_return_2 = shl_ln740_2_fu_2571_p3;

assign ap_return_3 = shl_ln740_3_fu_2578_p3;

assign ap_return_4 = shl_ln740_4_fu_2585_p3;

assign ap_return_5 = shl_ln740_5_fu_2592_p3;

assign ap_return_6 = shl_ln740_6_fu_2599_p3;

assign ap_return_7 = shl_ln740_7_fu_2606_p3;

assign ap_return_8 = shl_ln740_8_fu_2613_p3;

assign ap_return_9 = shl_ln740_9_fu_2620_p3;

assign grp_fu_521_p1 = grp_fu_256_p2;

assign grp_fu_531_p1 = grp_fu_257_p2;

assign grp_fu_541_p1 = grp_fu_257_p2;

assign grp_fu_551_p1 = grp_fu_256_p2;

assign grp_fu_561_p1 = grp_fu_257_p2;

assign or_ln_fu_2360_p3 = {{5'd17}, {lshr_ln717_2_reg_2799}};

assign r_V_0_fu_2377_p1 = p_read34_reg_2928;

assign r_V_1_fu_2441_p1 = p_read_21_reg_2781;

assign r_V_2_fu_843_p1 = p_read_20_reg_2769;

assign r_V_3_fu_916_p1 = p_read_19_reg_2805;

assign r_V_5_fu_1191_p1 = p_read_18_reg_2832;

assign r_V_6_fu_2068_p1 = p_read_17_reg_2863;

assign sext_ln1171_17_fu_898_p1 = $signed(sub_ln1171_12_reg_3005);

assign sext_ln1171_18_fu_1115_p1 = $signed(sub_ln1171_16_reg_3052);

assign sext_ln1171_19_fu_1477_p1 = $signed(sub_ln1171_18_reg_3092);

assign sext_ln1171_20_fu_2235_p1 = $signed(sub_ln1171_21_reg_3334);

assign sext_ln1171_21_fu_1500_p1 = $signed(sub_ln1171_23_reg_3103);

assign sext_ln1171_22_fu_723_p1 = $signed(sub_ln1171_25_reg_2883);

assign sext_ln1171_23_fu_794_p1 = $signed(sub_ln1171_27_reg_2908);

assign sext_ln1171_fu_1662_p1 = $signed(sub_ln1171_1_reg_3123);

assign sext_ln712_10_fu_2449_p1 = $signed(trunc_ln717_27_reg_3429);

assign sext_ln712_11_fu_2452_p1 = $signed(reg_591);

assign sext_ln712_12_fu_2494_p1 = $signed(reg_603);

assign sext_ln712_13_fu_1872_p1 = $signed(trunc_ln717_31_reg_3133);

assign sext_ln712_14_fu_1216_p1 = $signed(reg_599);

assign sext_ln712_15_fu_1875_p1 = $signed(trunc_ln717_29_reg_3128);

assign sext_ln712_16_fu_1878_p1 = $signed(trunc_ln717_33_reg_3138);

assign sext_ln712_17_fu_1567_p1 = $signed(trunc_ln717_34_reg_2979);

assign sext_ln712_18_fu_1881_p1 = $signed(trunc_ln717_35_reg_3143);

assign sext_ln712_19_fu_2498_p1 = $signed(reg_611);

assign sext_ln712_1_fu_2076_p1 = $signed(trunc_ln717_s_reg_3213);

assign sext_ln712_20_fu_2530_p1 = $signed(reg_611);

assign sext_ln712_21_fu_977_p1 = $signed(trunc_ln717_38_reg_3010);

assign sext_ln712_22_fu_1070_p1 = $signed(reg_607);

assign sext_ln712_23_fu_1888_p1 = $signed(reg_611);

assign sext_ln712_24_fu_2502_p1 = $signed(add_ln712_reg_3454);

assign sext_ln712_25_fu_1895_p1 = $signed(trunc_ln717_39_reg_3148);

assign sext_ln712_26_fu_1898_p1 = $signed(reg_603);

assign sext_ln712_27_fu_2094_p1 = $signed(trunc_ln717_42_reg_3243);

assign sext_ln712_28_fu_980_p1 = $signed(reg_615);

assign sext_ln712_29_fu_1074_p1 = $signed(reg_615);

assign sext_ln712_2_fu_2253_p1 = $signed(trunc_ln717_19_reg_3218);

assign sext_ln712_30_fu_1078_p1 = $signed(reg_619);

assign sext_ln712_31_fu_1892_p1 = $signed(trunc_ln717_43_reg_3153);

assign sext_ln712_32_fu_1220_p1 = $signed(reg_615);

assign sext_ln712_33_fu_1902_p1 = $signed(trunc_ln717_45_reg_3015);

assign sext_ln712_34_fu_1911_p1 = $signed(reg_607);

assign sext_ln712_35_fu_1583_p1 = $signed(trunc_ln717_53_reg_3087);

assign sext_ln712_36_fu_1915_p1 = $signed(reg_619);

assign sext_ln712_37_fu_1919_p1 = $signed(trunc_ln717_55_reg_3158);

assign sext_ln712_38_fu_2534_p1 = $signed(reg_603);

assign sext_ln712_39_fu_1586_p1 = $signed(reg_615);

assign sext_ln712_3_fu_2082_p1 = $signed(trunc_ln717_20_reg_3223);

assign sext_ln712_40_fu_1922_p1 = $signed(reg_615);

assign sext_ln712_41_fu_2256_p1 = $signed(trunc_ln717_60_reg_3032);

assign sext_ln712_42_fu_1580_p1 = $signed(trunc_ln717_49_reg_3082);

assign sext_ln712_43_fu_1224_p1 = $signed(trunc_ln717_63_reg_3062);

assign sext_ln712_44_fu_2337_p1 = $signed(trunc_ln717_64_reg_3394);

assign sext_ln712_45_fu_812_p1 = $signed(reg_599);

assign sext_ln712_46_fu_1926_p1 = $signed(trunc_ln717_66_reg_3168);

assign sext_ln712_47_fu_1929_p1 = $signed(trunc_ln717_62_reg_3163);

assign sext_ln712_48_fu_1082_p1 = $signed(trunc_ln717_57_reg_3027);

assign sext_ln712_49_fu_1590_p1 = $signed(trunc_ln717_61_reg_2858);

assign sext_ln712_4_fu_2333_p1 = $signed(reg_595);

assign sext_ln712_50_fu_1593_p1 = $signed(trunc_ln717_69_reg_2913);

assign sext_ln712_51_fu_2107_p1 = $signed(reg_599);

assign sext_ln712_52_fu_2259_p1 = $signed(reg_607);

assign sext_ln712_53_fu_2111_p1 = $signed(trunc_ln717_67_reg_2903);

assign sext_ln712_54_fu_2263_p1 = $signed(reg_611);

assign sext_ln712_55_fu_847_p1 = $signed(trunc_ln717_68_reg_2959);

assign sext_ln712_56_fu_2340_p1 = $signed(reg_611);

assign sext_ln712_57_fu_1935_p1 = $signed(trunc_ln717_75_reg_3173);

assign sext_ln712_58_fu_2114_p1 = $signed(reg_595);

assign sext_ln712_59_fu_1596_p1 = $signed(trunc_ln717_72_reg_2888);

assign sext_ln712_5_fu_2403_p1 = $signed(reg_599);

assign sext_ln712_60_fu_819_p1 = $signed(trunc_ln717_74_reg_2918);

assign sext_ln712_6_fu_2085_p1 = $signed(trunc_ln717_23_reg_3228);

assign sext_ln712_7_fu_2088_p1 = $signed(trunc_ln717_24_reg_3233);

assign sext_ln712_8_fu_2407_p1 = $signed(reg_603);

assign sext_ln712_9_fu_2445_p1 = $signed(reg_607);

assign sext_ln712_fu_2400_p1 = $signed(trunc_ln_reg_3414);

assign sext_ln740_10_fu_2367_p1 = $signed(or_ln_fu_2360_p3);

assign sext_ln740_11_fu_2467_p1 = $signed(add_ln740_24_reg_2989);

assign sext_ln740_12_fu_2152_p1 = $signed(add_ln740_38_reg_3279);

assign sext_ln740_13_fu_2272_p1 = $signed(add_ln740_39_reg_3359);

assign sext_ln740_14_fu_2180_p1 = $signed(add_ln740_45_reg_3289);

assign sext_ln740_15_fu_1979_p1 = $signed(add_ln740_47_reg_3193);

assign sext_ln740_16_fu_1982_p1 = $signed(add_ln740_48_reg_3198);

assign sext_ln740_17_fu_865_p1 = $signed(add_ln740_56_reg_2969);

assign sext_ln740_18_fu_2476_p1 = $signed(add_ln740_72_reg_3314);

assign sext_ln740_19_fu_2226_p1 = $signed(add_ln740_75_reg_3319);

assign sext_ln740_1_fu_2547_p1 = $signed(add_ln740_19_reg_3349);

assign sext_ln740_20_fu_2485_p1 = $signed(add_ln740_76_reg_3389);

assign sext_ln740_2_fu_2538_p1 = $signed(add_ln740_15_reg_3344);

assign sext_ln740_3_fu_1095_p1 = $signed(add_ln740_28_reg_3042);

assign sext_ln740_4_fu_1605_p1 = $signed(add_ln740_33_reg_3108);

assign sext_ln740_5_fu_856_p1 = $signed(add_ln740_23_reg_2964);

assign sext_ln740_6_fu_2171_p1 = $signed(add_ln740_43_reg_3284);

assign sext_ln740_7_fu_2510_p1 = $signed(add_ln740_44_reg_3364);

assign sext_ln740_8_fu_2292_p1 = $signed(add_ln740_53_reg_3374);

assign sext_ln740_9_fu_868_p1 = $signed(add_ln740_57_reg_2974);

assign sext_ln740_fu_2127_p1 = $signed(add_ln740_18_reg_3263);

assign shl_ln1171_10_fu_1430_p3 = {{p_read_20_reg_2769}, {1'd0}};

assign shl_ln1171_11_fu_1006_p3 = {{p_read_19_reg_2805}, {5'd0}};

assign shl_ln1171_12_fu_1118_p3 = {{p_read_19_reg_2805}, {1'd0}};

assign shl_ln1171_13_fu_1174_p3 = {{p_read_19_reg_2805}, {6'd0}};

assign shl_ln1171_14_fu_1043_p3 = {{p_read_18_reg_2832}, {7'd0}};

assign shl_ln1171_15_fu_2051_p3 = {{p_read_18_reg_2832}, {5'd0}};

assign shl_ln1171_16_fu_1195_p3 = {{p_read_18_reg_2832}, {6'd0}};

assign shl_ln1171_17_fu_1503_p3 = {{p_read_18_reg_2832}, {2'd0}};

assign shl_ln1171_18_fu_690_p3 = {{ap_port_reg_p_read5}, {5'd0}};

assign shl_ln1171_19_fu_741_p3 = {{p_read_17_reg_2863}, {3'd0}};

assign shl_ln1171_1_fu_1254_p3 = {{p_read34_reg_2928}, {6'd0}};

assign shl_ln1171_20_fu_758_p3 = {{p_read_17_reg_2863}, {1'd0}};

assign shl_ln1171_21_fu_1530_p3 = {{p_read_17_reg_2863}, {7'd0}};

assign shl_ln1171_2_fu_1392_p3 = {{p_read_20_reg_2769}, {7'd0}};

assign shl_ln1171_3_fu_1685_p3 = {{p_read34_reg_2928}, {3'd0}};

assign shl_ln1171_4_fu_1725_p3 = {{p_read34_reg_2928}, {1'd0}};

assign shl_ln1171_5_fu_1756_p3 = {{p_read34_reg_2928}, {2'd0}};

assign shl_ln1171_6_fu_1287_p3 = {{p_read_21_reg_2781}, {7'd0}};

assign shl_ln1171_7_fu_1314_p3 = {{p_read_21_reg_2781}, {6'd0}};

assign shl_ln1171_8_fu_1325_p3 = {{p_read_21_reg_2781}, {4'd0}};

assign shl_ln1171_9_fu_1419_p3 = {{p_read_20_reg_2769}, {6'd0}};

assign shl_ln1171_s_fu_881_p3 = {{p_read_20_reg_2769}, {5'd0}};

assign shl_ln1_fu_2306_p3 = {{p_read34_reg_2928}, {7'd0}};

assign shl_ln2_fu_2556_p3 = {{add_ln740_fu_2550_p2}, {2'd0}};

assign shl_ln717_1_fu_1712_p3 = {{p_read34_reg_2928}, {5'd0}};

assign shl_ln717_2_fu_1274_p3 = {{p_read_21_reg_2781}, {5'd0}};

assign shl_ln717_3_fu_1802_p3 = {{p_read_21_reg_2781}, {2'd0}};

assign shl_ln717_4_fu_1832_p3 = {{p_read_20_reg_2769}, {3'd0}};

assign shl_ln717_5_fu_1457_p3 = {{p_read_19_reg_2805}, {4'd0}};

assign shl_ln717_6_fu_999_p3 = {{p_read_19_reg_2805}, {2'd0}};

assign shl_ln717_7_fu_923_p3 = {{p_read_18_reg_2832}, {3'd0}};

assign shl_ln717_8_fu_934_p3 = {{p_read_18_reg_2832}, {1'd0}};

assign shl_ln740_10_fu_2634_p3 = {{add_ln740_11_reg_3444}, {2'd0}};

assign shl_ln740_11_fu_2641_p3 = {{add_ln740_12_reg_3464}, {2'd0}};

assign shl_ln740_12_fu_2648_p3 = {{add_ln740_13_reg_3479}, {2'd0}};

assign shl_ln740_13_fu_2665_p3 = {{add_ln740_14_fu_2660_p2}, {2'd0}};

assign shl_ln740_1_fu_2564_p3 = {{add_ln740_1_reg_3459}, {2'd0}};

assign shl_ln740_2_fu_2571_p3 = {{add_ln740_2_reg_3434}, {2'd0}};

assign shl_ln740_3_fu_2578_p3 = {{add_ln740_3_reg_3354}, {2'd0}};

assign shl_ln740_4_fu_2585_p3 = {{add_ln740_4_reg_3399}, {2'd0}};

assign shl_ln740_5_fu_2592_p3 = {{add_ln740_5_reg_3474}, {2'd0}};

assign shl_ln740_6_fu_2599_p3 = {{add_ln740_6_reg_3369}, {2'd0}};

assign shl_ln740_7_fu_2606_p3 = {{add_ln740_7_reg_3419}, {2'd0}};

assign shl_ln740_8_fu_2613_p3 = {{add_ln740_8_reg_3439}, {2'd0}};

assign shl_ln740_9_fu_2620_p3 = {{add_ln740_9_reg_3379}, {2'd0}};

assign shl_ln740_s_fu_2627_p3 = {{add_ln740_10_reg_3384}, {2'd0}};

assign shl_ln_fu_1635_p3 = {{p_read34_reg_2928}, {4'd0}};

assign sub_ln1171_10_fu_1360_p2 = (zext_ln1171_17_fu_1352_p1 - zext_ln1171_14_fu_1294_p1);

assign sub_ln1171_11_fu_1376_p2 = (14'd0 - zext_ln1171_18_fu_1356_p1);

assign sub_ln1171_12_fu_892_p2 = (14'd0 - zext_ln1171_21_fu_888_p1);

assign sub_ln1171_13_fu_901_p2 = ($signed(sext_ln1171_17_fu_898_p1) - $signed(zext_ln1171_19_reg_2999));

assign sub_ln1171_14_fu_1403_p2 = (16'd0 - zext_ln1171_22_fu_1399_p1);

assign sub_ln1171_15_fu_1441_p2 = (zext_ln1171_24_fu_1437_p1 - zext_ln1171_23_fu_1426_p1);

assign sub_ln1171_16_fu_1017_p2 = (14'd0 - zext_ln1171_28_fu_1013_p1);

assign sub_ln1171_17_fu_1129_p2 = ($signed(sext_ln1171_18_fu_1115_p1) - $signed(zext_ln1171_29_fu_1125_p1));

assign sub_ln1171_18_fu_1185_p2 = (15'd0 - zext_ln1171_32_fu_1181_p1);

assign sub_ln1171_19_fu_1484_p2 = ($signed(sext_ln1171_19_fu_1477_p1) - $signed(zext_ln1171_33_fu_1480_p1));

assign sub_ln1171_1_fu_1265_p2 = (15'd0 - zext_ln1171_5_fu_1261_p1);

assign sub_ln1171_20_fu_1054_p2 = (16'd0 - zext_ln1171_39_fu_1050_p1);

assign sub_ln1171_21_fu_2062_p2 = (14'd0 - zext_ln1171_40_fu_2058_p1);

assign sub_ln1171_22_fu_2238_p2 = ($signed(sext_ln1171_20_fu_2235_p1) - $signed(zext_ln1171_37_reg_2851));

assign sub_ln1171_23_fu_1206_p2 = (15'd0 - zext_ln1171_41_fu_1202_p1);

assign sub_ln1171_24_fu_1514_p2 = ($signed(sext_ln1171_21_fu_1500_p1) - $signed(zext_ln1171_42_fu_1510_p1));

assign sub_ln1171_25_fu_702_p2 = (14'd0 - zext_ln1171_46_fu_698_p1);

assign sub_ln1171_26_fu_726_p2 = ($signed(sext_ln1171_22_fu_723_p1) - $signed(zext_ln1171_44_reg_2873));

assign sub_ln1171_27_fu_752_p2 = (12'd0 - zext_ln1171_47_fu_748_p1);

assign sub_ln1171_28_fu_797_p2 = ($signed(sext_ln1171_23_fu_794_p1) - $signed(zext_ln1171_45_reg_2878));

assign sub_ln1171_29_fu_769_p2 = (zext_ln1171_48_fu_765_p1 - zext_ln1171_47_fu_748_p1);

assign sub_ln1171_2_fu_1669_p2 = ($signed(sext_ln1171_fu_1662_p1) - $signed(zext_ln1171_6_fu_1665_p1));

assign sub_ln1171_30_fu_1541_p2 = (16'd0 - zext_ln1171_49_fu_1537_p1);

assign sub_ln1171_31_fu_1159_p2 = (r_V_3_reg_3020 - zext_ln1171_31_fu_1155_p1);

assign sub_ln1171_32_fu_961_p2 = (zext_ln1171_36_fu_920_p1 - zext_ln717_8_fu_930_p1);

assign sub_ln1171_3_fu_1696_p2 = ($signed(sext_ln1171_fu_1662_p1) - $signed(zext_ln1171_7_fu_1692_p1));

assign sub_ln1171_4_fu_1740_p2 = (zext_ln1171_9_fu_1736_p1 - zext_ln717_fu_1642_p1);

assign sub_ln1171_5_fu_1767_p2 = ($signed(sext_ln1171_fu_1662_p1) - $signed(zext_ln1171_10_fu_1763_p1));

assign sub_ln1171_6_fu_1783_p2 = (10'd0 - zext_ln1171_8_fu_1732_p1);

assign sub_ln1171_7_fu_2384_p2 = (9'd0 - zext_ln1171_1_fu_2381_p1);

assign sub_ln1171_8_fu_1298_p2 = (16'd0 - zext_ln1171_14_fu_1294_p1);

assign sub_ln1171_9_fu_1336_p2 = (zext_ln1171_16_fu_1332_p1 - zext_ln1171_15_fu_1321_p1);

assign sub_ln1171_fu_2317_p2 = (16'd0 - zext_ln1171_4_fu_2313_p1);

assign sub_ln717_1_fu_1281_p2 = (shl_ln717_2_fu_1274_p3 - zext_ln1171_11_fu_1271_p1);

assign sub_ln717_2_fu_1843_p2 = (zext_ln717_4_fu_1839_p1 - zext_ln717_3_fu_1829_p1);

assign sub_ln717_3_fu_1471_p2 = (zext_ln717_5_fu_1464_p1 - zext_ln717_6_fu_1468_p1);

assign sub_ln717_4_fu_945_p2 = (zext_ln717_8_fu_930_p1 - zext_ln717_9_fu_941_p1);

assign sub_ln717_fu_1719_p2 = (shl_ln717_1_fu_1712_p3 - zext_ln1171_fu_1632_p1);

assign tmp_fu_1148_p3 = {{p_read_19_reg_2805}, {7'd0}};

assign trunc_ln712_9_fu_708_p1 = grp_fu_256_p2;

assign zext_ln1171_10_fu_1763_p1 = shl_ln1171_5_fu_1756_p3;

assign zext_ln1171_11_fu_1271_p1 = p_read_21_reg_2781;

assign zext_ln1171_12_fu_790_p1 = p_read_21_reg_2781;

assign zext_ln1171_13_fu_623_p1 = p_read1;

assign zext_ln1171_14_fu_1294_p1 = shl_ln1171_6_fu_1287_p3;

assign zext_ln1171_15_fu_1321_p1 = shl_ln1171_7_fu_1314_p3;

assign zext_ln1171_16_fu_1332_p1 = shl_ln1171_8_fu_1325_p3;

assign zext_ln1171_17_fu_1352_p1 = shl_ln717_2_fu_1274_p3;

assign zext_ln1171_18_fu_1356_p1 = shl_ln717_2_fu_1274_p3;

assign zext_ln1171_19_fu_877_p1 = p_read_20_reg_2769;

assign zext_ln1171_1_fu_2381_p1 = p_read34_reg_2928;

assign zext_ln1171_20_fu_628_p1 = p_read2;

assign zext_ln1171_21_fu_888_p1 = shl_ln1171_s_fu_881_p3;

assign zext_ln1171_22_fu_1399_p1 = shl_ln1171_2_fu_1392_p3;

assign zext_ln1171_23_fu_1426_p1 = shl_ln1171_9_fu_1419_p3;

assign zext_ln1171_24_fu_1437_p1 = shl_ln1171_10_fu_1430_p3;

assign zext_ln1171_25_fu_663_p1 = p_read_19_reg_2805;

assign zext_ln1171_26_fu_643_p1 = ap_port_reg_p_read3;

assign zext_ln1171_27_fu_648_p1 = ap_port_reg_p_read3;

assign zext_ln1171_28_fu_1013_p1 = shl_ln1171_11_fu_1006_p3;

assign zext_ln1171_29_fu_1125_p1 = shl_ln1171_12_fu_1118_p3;

assign zext_ln1171_2_fu_2301_p1 = p_read34_reg_2928;

assign zext_ln1171_30_fu_1023_p1 = shl_ln717_6_fu_999_p3;

assign zext_ln1171_31_fu_1155_p1 = tmp_fu_1148_p3;

assign zext_ln1171_32_fu_1181_p1 = shl_ln1171_13_fu_1174_p3;

assign zext_ln1171_33_fu_1480_p1 = shl_ln717_5_fu_1457_p3;

assign zext_ln1171_34_fu_667_p1 = ap_port_reg_p_read4;

assign zext_ln1171_35_fu_672_p1 = p_read_18_reg_2832;

assign zext_ln1171_36_fu_920_p1 = p_read_18_reg_2832;

assign zext_ln1171_37_fu_676_p1 = p_read_18_reg_2832;

assign zext_ln1171_38_fu_840_p1 = lshr_ln717_s_reg_2948;

assign zext_ln1171_39_fu_1050_p1 = shl_ln1171_14_fu_1043_p3;

assign zext_ln1171_3_fu_785_p1 = ap_port_reg_p_read;

assign zext_ln1171_40_fu_2058_p1 = shl_ln1171_15_fu_2051_p3;

assign zext_ln1171_41_fu_1202_p1 = shl_ln1171_16_fu_1195_p3;

assign zext_ln1171_42_fu_1510_p1 = shl_ln1171_17_fu_1503_p3;

assign zext_ln1171_43_fu_718_p1 = p_read_17_reg_2863;

assign zext_ln1171_44_fu_680_p1 = ap_port_reg_p_read5;

assign zext_ln1171_45_fu_685_p1 = ap_port_reg_p_read5;

assign zext_ln1171_46_fu_698_p1 = shl_ln1171_18_fu_690_p3;

assign zext_ln1171_47_fu_748_p1 = shl_ln1171_19_fu_741_p3;

assign zext_ln1171_48_fu_765_p1 = shl_ln1171_20_fu_758_p3;

assign zext_ln1171_49_fu_1537_p1 = shl_ln1171_21_fu_1530_p3;

assign zext_ln1171_4_fu_2313_p1 = shl_ln1_fu_2306_p3;

assign zext_ln1171_5_fu_1261_p1 = shl_ln1171_1_fu_1254_p3;

assign zext_ln1171_6_fu_1665_p1 = shl_ln_fu_1635_p3;

assign zext_ln1171_7_fu_1692_p1 = shl_ln1171_3_fu_1685_p3;

assign zext_ln1171_8_fu_1732_p1 = shl_ln1171_4_fu_1725_p3;

assign zext_ln1171_9_fu_1736_p1 = shl_ln1171_4_fu_1725_p3;

assign zext_ln1171_fu_1632_p1 = p_read34_reg_2928;

assign zext_ln712_10_fu_2104_p1 = lshr_ln717_4_reg_2817;

assign zext_ln712_11_fu_816_p1 = trunc_ln712_7_reg_2846;

assign zext_ln712_12_fu_1085_p1 = $unsigned(sext_ln712_48_fu_1082_p1);

assign zext_ln712_13_fu_984_p1 = trunc_ln712_9_reg_2893;

assign zext_ln712_14_fu_1932_p1 = p_read_17_reg_2863;

assign zext_ln712_1_fu_2079_p1 = trunc_ln3_reg_3248;

assign zext_ln712_2_fu_1869_p1 = trunc_ln712_1_reg_3178;

assign zext_ln712_3_fu_1212_p1 = reg_591;

assign zext_ln712_4_fu_2091_p1 = lshr_ln717_1_reg_3238;

assign zext_ln712_5_fu_1884_p1 = reg_595;

assign zext_ln712_6_fu_2097_p1 = $unsigned(sext_ln712_27_fu_2094_p1);

assign zext_ln712_7_fu_2101_p1 = lshr_ln717_2_reg_2799;

assign zext_ln712_8_fu_1905_p1 = trunc_ln712_5_reg_3183;

assign zext_ln712_9_fu_1908_p1 = trunc_ln712_6_reg_2827;

assign zext_ln712_fu_2073_p1 = lshr_ln_reg_3208;

assign zext_ln717_1_fu_1799_p1 = p_read_21_reg_2781;

assign zext_ln717_2_fu_1809_p1 = shl_ln717_3_fu_1802_p3;

assign zext_ln717_3_fu_1829_p1 = p_read_20_reg_2769;

assign zext_ln717_4_fu_1839_p1 = shl_ln717_4_fu_1832_p3;

assign zext_ln717_5_fu_1464_p1 = shl_ln717_5_fu_1457_p3;

assign zext_ln717_6_fu_1468_p1 = shl_ln717_6_reg_3047;

assign zext_ln717_7_fu_1145_p1 = lshr_ln717_3_reg_3057;

assign zext_ln717_8_fu_930_p1 = shl_ln717_7_fu_923_p3;

assign zext_ln717_9_fu_941_p1 = shl_ln717_8_fu_934_p3;

assign zext_ln717_fu_1642_p1 = shl_ln_fu_1635_p3;

assign zext_ln740_1_fu_2167_p1 = add_ln740_42_fu_2161_p2;

assign zext_ln740_2_fu_1245_p1 = add_ln740_62_reg_3077;

assign zext_ln740_fu_2124_p1 = add_ln740_17_reg_3258;

always @ (posedge ap_clk) begin
    zext_ln1171_13_reg_2794[13:8] <= 6'b000000;
    zext_ln1171_37_reg_2851[14:8] <= 7'b0000000;
    zext_ln1171_44_reg_2873[14:8] <= 7'b0000000;
    zext_ln1171_45_reg_2878[12:8] <= 5'b00000;
    sub_ln1171_25_reg_2883[4:0] <= 5'b00000;
    zext_ln1171_43_reg_2898[13:8] <= 6'b000000;
    sub_ln1171_27_reg_2908[2:0] <= 3'b000;
    zext_ln1171_3_reg_2943[13:8] <= 6'b000000;
    zext_ln1171_12_reg_2953[14:8] <= 7'b0000000;
    r_V_2_reg_2984[15:8] <= 8'b00000000;
    zext_ln1171_19_reg_2999[14:8] <= 7'b0000000;
    sub_ln1171_12_reg_3005[4:0] <= 5'b00000;
    r_V_3_reg_3020[15:8] <= 8'b00000000;
    shl_ln717_6_reg_3047[1:0] <= 2'b00;
    sub_ln1171_16_reg_3052[4:0] <= 5'b00000;
    sub_ln1171_18_reg_3092[5:0] <= 6'b000000;
    r_V_5_reg_3097[15:8] <= 8'b00000000;
    sub_ln1171_23_reg_3103[5:0] <= 6'b000000;
    sub_ln1171_1_reg_3123[5:0] <= 6'b000000;
    add_ln740_25_reg_3268[3:0] <= 4'b0000;
    sub_ln1171_21_reg_3334[4:0] <= 5'b00000;
    r_V_6_reg_3339[15:8] <= 8'b00000000;
    r_V_1_reg_3449[15:8] <= 8'b00000000;
end

endmodule //myproject_dense_latency_ap_ufixed_8_1_4_0_0_ap_fixed_16_4_5_3_0_config5_s
