// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_relu_ap_fixed_16_4_5_3_0_ap_ufixed_8_0_4_0_0_relu_config4_s (
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4
);


output   ap_ready;
input  [15:0] p_read;
input  [15:0] p_read1;
input  [15:0] p_read2;
input  [15:0] p_read3;
input  [15:0] p_read4;
output  [7:0] ap_return_0;
output  [7:0] ap_return_1;
output  [7:0] ap_return_2;
output  [7:0] ap_return_3;
output  [7:0] ap_return_4;

wire   [2:0] trunc_ln727_fu_116_p1;
wire   [0:0] tmp_fu_100_p3;
wire   [0:0] icmp_ln727_fu_120_p2;
wire   [0:0] or_ln412_fu_134_p2;
wire   [0:0] tmp_13_fu_108_p3;
wire   [0:0] and_ln412_fu_140_p2;
wire   [7:0] trunc_ln3_fu_90_p4;
wire   [7:0] zext_ln415_fu_146_p1;
wire   [7:0] add_ln415_fu_150_p2;
wire   [3:0] p_Result_s_fu_164_p4;
wire   [0:0] tmp_15_fu_156_p3;
wire   [0:0] icmp_ln777_fu_180_p2;
wire   [0:0] icmp_ln1049_fu_174_p2;
wire   [0:0] tmp_14_fu_126_p3;
wire   [0:0] select_ln787_fu_186_p3;
wire   [0:0] select_ln403_fu_194_p3;
wire   [0:0] icmp_ln1547_fu_84_p2;
wire   [7:0] select_ln394_fu_202_p3;
wire   [2:0] trunc_ln727_2_fu_250_p1;
wire   [0:0] tmp_16_fu_234_p3;
wire   [0:0] icmp_ln727_2_fu_254_p2;
wire   [0:0] or_ln412_1_fu_268_p2;
wire   [0:0] tmp_17_fu_242_p3;
wire   [0:0] and_ln412_2_fu_274_p2;
wire   [7:0] trunc_ln717_3_fu_224_p4;
wire   [7:0] zext_ln415_1_fu_280_p1;
wire   [7:0] add_ln415_2_fu_284_p2;
wire   [3:0] p_Result_39_1_fu_298_p4;
wire   [0:0] tmp_19_fu_290_p3;
wire   [0:0] icmp_ln777_2_fu_314_p2;
wire   [0:0] icmp_ln1049_2_fu_308_p2;
wire   [0:0] tmp_18_fu_260_p3;
wire   [0:0] select_ln787_1_fu_320_p3;
wire   [0:0] select_ln403_2_fu_328_p3;
wire   [0:0] icmp_ln1547_1_fu_218_p2;
wire   [7:0] select_ln394_2_fu_336_p3;
wire   [2:0] trunc_ln727_3_fu_384_p1;
wire   [0:0] tmp_20_fu_368_p3;
wire   [0:0] icmp_ln727_3_fu_388_p2;
wire   [0:0] or_ln412_2_fu_402_p2;
wire   [0:0] tmp_21_fu_376_p3;
wire   [0:0] and_ln412_3_fu_408_p2;
wire   [7:0] trunc_ln717_4_fu_358_p4;
wire   [7:0] zext_ln415_2_fu_414_p1;
wire   [7:0] add_ln415_3_fu_418_p2;
wire   [3:0] p_Result_39_2_fu_432_p4;
wire   [0:0] tmp_23_fu_424_p3;
wire   [0:0] icmp_ln777_3_fu_448_p2;
wire   [0:0] icmp_ln1049_3_fu_442_p2;
wire   [0:0] tmp_22_fu_394_p3;
wire   [0:0] select_ln787_2_fu_454_p3;
wire   [0:0] select_ln403_3_fu_462_p3;
wire   [0:0] icmp_ln1547_2_fu_352_p2;
wire   [7:0] select_ln394_3_fu_470_p3;
wire   [2:0] trunc_ln727_4_fu_518_p1;
wire   [0:0] tmp_24_fu_502_p3;
wire   [0:0] icmp_ln727_4_fu_522_p2;
wire   [0:0] or_ln412_3_fu_536_p2;
wire   [0:0] tmp_25_fu_510_p3;
wire   [0:0] and_ln412_4_fu_542_p2;
wire   [7:0] trunc_ln717_5_fu_492_p4;
wire   [7:0] zext_ln415_3_fu_548_p1;
wire   [7:0] add_ln415_4_fu_552_p2;
wire   [3:0] p_Result_39_3_fu_566_p4;
wire   [0:0] tmp_27_fu_558_p3;
wire   [0:0] icmp_ln777_4_fu_582_p2;
wire   [0:0] icmp_ln1049_4_fu_576_p2;
wire   [0:0] tmp_26_fu_528_p3;
wire   [0:0] select_ln787_3_fu_588_p3;
wire   [0:0] select_ln403_4_fu_596_p3;
wire   [0:0] icmp_ln1547_3_fu_486_p2;
wire   [7:0] select_ln394_4_fu_604_p3;
wire   [2:0] trunc_ln727_5_fu_652_p1;
wire   [0:0] tmp_28_fu_636_p3;
wire   [0:0] icmp_ln727_5_fu_656_p2;
wire   [0:0] or_ln412_4_fu_670_p2;
wire   [0:0] tmp_29_fu_644_p3;
wire   [0:0] and_ln412_5_fu_676_p2;
wire   [7:0] trunc_ln717_6_fu_626_p4;
wire   [7:0] zext_ln415_4_fu_682_p1;
wire   [7:0] add_ln415_5_fu_686_p2;
wire   [3:0] p_Result_39_4_fu_700_p4;
wire   [0:0] tmp_31_fu_692_p3;
wire   [0:0] icmp_ln777_5_fu_716_p2;
wire   [0:0] icmp_ln1049_5_fu_710_p2;
wire   [0:0] tmp_30_fu_662_p3;
wire   [0:0] select_ln787_4_fu_722_p3;
wire   [0:0] select_ln403_5_fu_730_p3;
wire   [0:0] icmp_ln1547_4_fu_620_p2;
wire   [7:0] select_ln394_5_fu_738_p3;
wire   [7:0] select_ln1547_fu_210_p3;
wire   [7:0] select_ln1547_2_fu_344_p3;
wire   [7:0] select_ln1547_3_fu_478_p3;
wire   [7:0] select_ln1547_4_fu_612_p3;
wire   [7:0] select_ln1547_5_fu_746_p3;
wire    ap_ce_reg;

assign add_ln415_2_fu_284_p2 = (trunc_ln717_3_fu_224_p4 + zext_ln415_1_fu_280_p1);

assign add_ln415_3_fu_418_p2 = (trunc_ln717_4_fu_358_p4 + zext_ln415_2_fu_414_p1);

assign add_ln415_4_fu_552_p2 = (trunc_ln717_5_fu_492_p4 + zext_ln415_3_fu_548_p1);

assign add_ln415_5_fu_686_p2 = (trunc_ln717_6_fu_626_p4 + zext_ln415_4_fu_682_p1);

assign add_ln415_fu_150_p2 = (trunc_ln3_fu_90_p4 + zext_ln415_fu_146_p1);

assign and_ln412_2_fu_274_p2 = (tmp_17_fu_242_p3 & or_ln412_1_fu_268_p2);

assign and_ln412_3_fu_408_p2 = (tmp_21_fu_376_p3 & or_ln412_2_fu_402_p2);

assign and_ln412_4_fu_542_p2 = (tmp_25_fu_510_p3 & or_ln412_3_fu_536_p2);

assign and_ln412_5_fu_676_p2 = (tmp_29_fu_644_p3 & or_ln412_4_fu_670_p2);

assign and_ln412_fu_140_p2 = (tmp_13_fu_108_p3 & or_ln412_fu_134_p2);

assign ap_ready = 1'b1;

assign ap_return_0 = select_ln1547_fu_210_p3;

assign ap_return_1 = select_ln1547_2_fu_344_p3;

assign ap_return_2 = select_ln1547_3_fu_478_p3;

assign ap_return_3 = select_ln1547_4_fu_612_p3;

assign ap_return_4 = select_ln1547_5_fu_746_p3;

assign icmp_ln1049_2_fu_308_p2 = ((p_Result_39_1_fu_298_p4 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln1049_3_fu_442_p2 = ((p_Result_39_2_fu_432_p4 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln1049_4_fu_576_p2 = ((p_Result_39_3_fu_566_p4 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln1049_5_fu_710_p2 = ((p_Result_39_4_fu_700_p4 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln1049_fu_174_p2 = ((p_Result_s_fu_164_p4 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln1547_1_fu_218_p2 = (($signed(p_read1) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1547_2_fu_352_p2 = (($signed(p_read2) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1547_3_fu_486_p2 = (($signed(p_read3) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1547_4_fu_620_p2 = (($signed(p_read4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1547_fu_84_p2 = (($signed(p_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln727_2_fu_254_p2 = ((trunc_ln727_2_fu_250_p1 != 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln727_3_fu_388_p2 = ((trunc_ln727_3_fu_384_p1 != 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln727_4_fu_522_p2 = ((trunc_ln727_4_fu_518_p1 != 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln727_5_fu_656_p2 = ((trunc_ln727_5_fu_652_p1 != 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln727_fu_120_p2 = ((trunc_ln727_fu_116_p1 != 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln777_2_fu_314_p2 = ((p_Result_39_1_fu_298_p4 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln777_3_fu_448_p2 = ((p_Result_39_2_fu_432_p4 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln777_4_fu_582_p2 = ((p_Result_39_3_fu_566_p4 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln777_5_fu_716_p2 = ((p_Result_39_4_fu_700_p4 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln777_fu_180_p2 = ((p_Result_s_fu_164_p4 == 4'd0) ? 1'b1 : 1'b0);

assign or_ln412_1_fu_268_p2 = (tmp_16_fu_234_p3 | icmp_ln727_2_fu_254_p2);

assign or_ln412_2_fu_402_p2 = (tmp_20_fu_368_p3 | icmp_ln727_3_fu_388_p2);

assign or_ln412_3_fu_536_p2 = (tmp_24_fu_502_p3 | icmp_ln727_4_fu_522_p2);

assign or_ln412_4_fu_670_p2 = (tmp_28_fu_636_p3 | icmp_ln727_5_fu_656_p2);

assign or_ln412_fu_134_p2 = (tmp_fu_100_p3 | icmp_ln727_fu_120_p2);

assign p_Result_39_1_fu_298_p4 = {{p_read1[15:12]}};

assign p_Result_39_2_fu_432_p4 = {{p_read2[15:12]}};

assign p_Result_39_3_fu_566_p4 = {{p_read3[15:12]}};

assign p_Result_39_4_fu_700_p4 = {{p_read4[15:12]}};

assign p_Result_s_fu_164_p4 = {{p_read[15:12]}};

assign select_ln1547_2_fu_344_p3 = ((icmp_ln1547_1_fu_218_p2[0:0] == 1'b1) ? select_ln394_2_fu_336_p3 : 8'd0);

assign select_ln1547_3_fu_478_p3 = ((icmp_ln1547_2_fu_352_p2[0:0] == 1'b1) ? select_ln394_3_fu_470_p3 : 8'd0);

assign select_ln1547_4_fu_612_p3 = ((icmp_ln1547_3_fu_486_p2[0:0] == 1'b1) ? select_ln394_4_fu_604_p3 : 8'd0);

assign select_ln1547_5_fu_746_p3 = ((icmp_ln1547_4_fu_620_p2[0:0] == 1'b1) ? select_ln394_5_fu_738_p3 : 8'd0);

assign select_ln1547_fu_210_p3 = ((icmp_ln1547_fu_84_p2[0:0] == 1'b1) ? select_ln394_fu_202_p3 : 8'd0);

assign select_ln394_2_fu_336_p3 = ((select_ln403_2_fu_328_p3[0:0] == 1'b1) ? add_ln415_2_fu_284_p2 : 8'd255);

assign select_ln394_3_fu_470_p3 = ((select_ln403_3_fu_462_p3[0:0] == 1'b1) ? add_ln415_3_fu_418_p2 : 8'd255);

assign select_ln394_4_fu_604_p3 = ((select_ln403_4_fu_596_p3[0:0] == 1'b1) ? add_ln415_4_fu_552_p2 : 8'd255);

assign select_ln394_5_fu_738_p3 = ((select_ln403_5_fu_730_p3[0:0] == 1'b1) ? add_ln415_5_fu_686_p2 : 8'd255);

assign select_ln394_fu_202_p3 = ((select_ln403_fu_194_p3[0:0] == 1'b1) ? add_ln415_fu_150_p2 : 8'd255);

assign select_ln403_2_fu_328_p3 = ((tmp_18_fu_260_p3[0:0] == 1'b1) ? select_ln787_1_fu_320_p3 : icmp_ln777_2_fu_314_p2);

assign select_ln403_3_fu_462_p3 = ((tmp_22_fu_394_p3[0:0] == 1'b1) ? select_ln787_2_fu_454_p3 : icmp_ln777_3_fu_448_p2);

assign select_ln403_4_fu_596_p3 = ((tmp_26_fu_528_p3[0:0] == 1'b1) ? select_ln787_3_fu_588_p3 : icmp_ln777_4_fu_582_p2);

assign select_ln403_5_fu_730_p3 = ((tmp_30_fu_662_p3[0:0] == 1'b1) ? select_ln787_4_fu_722_p3 : icmp_ln777_5_fu_716_p2);

assign select_ln403_fu_194_p3 = ((tmp_14_fu_126_p3[0:0] == 1'b1) ? select_ln787_fu_186_p3 : icmp_ln777_fu_180_p2);

assign select_ln787_1_fu_320_p3 = ((tmp_19_fu_290_p3[0:0] == 1'b1) ? icmp_ln777_2_fu_314_p2 : icmp_ln1049_2_fu_308_p2);

assign select_ln787_2_fu_454_p3 = ((tmp_23_fu_424_p3[0:0] == 1'b1) ? icmp_ln777_3_fu_448_p2 : icmp_ln1049_3_fu_442_p2);

assign select_ln787_3_fu_588_p3 = ((tmp_27_fu_558_p3[0:0] == 1'b1) ? icmp_ln777_4_fu_582_p2 : icmp_ln1049_4_fu_576_p2);

assign select_ln787_4_fu_722_p3 = ((tmp_31_fu_692_p3[0:0] == 1'b1) ? icmp_ln777_5_fu_716_p2 : icmp_ln1049_5_fu_710_p2);

assign select_ln787_fu_186_p3 = ((tmp_15_fu_156_p3[0:0] == 1'b1) ? icmp_ln777_fu_180_p2 : icmp_ln1049_fu_174_p2);

assign tmp_13_fu_108_p3 = p_read[32'd3];

assign tmp_14_fu_126_p3 = p_read[32'd11];

assign tmp_15_fu_156_p3 = add_ln415_fu_150_p2[32'd7];

assign tmp_16_fu_234_p3 = p_read1[32'd4];

assign tmp_17_fu_242_p3 = p_read1[32'd3];

assign tmp_18_fu_260_p3 = p_read1[32'd11];

assign tmp_19_fu_290_p3 = add_ln415_2_fu_284_p2[32'd7];

assign tmp_20_fu_368_p3 = p_read2[32'd4];

assign tmp_21_fu_376_p3 = p_read2[32'd3];

assign tmp_22_fu_394_p3 = p_read2[32'd11];

assign tmp_23_fu_424_p3 = add_ln415_3_fu_418_p2[32'd7];

assign tmp_24_fu_502_p3 = p_read3[32'd4];

assign tmp_25_fu_510_p3 = p_read3[32'd3];

assign tmp_26_fu_528_p3 = p_read3[32'd11];

assign tmp_27_fu_558_p3 = add_ln415_4_fu_552_p2[32'd7];

assign tmp_28_fu_636_p3 = p_read4[32'd4];

assign tmp_29_fu_644_p3 = p_read4[32'd3];

assign tmp_30_fu_662_p3 = p_read4[32'd11];

assign tmp_31_fu_692_p3 = add_ln415_5_fu_686_p2[32'd7];

assign tmp_fu_100_p3 = p_read[32'd4];

assign trunc_ln3_fu_90_p4 = {{p_read[11:4]}};

assign trunc_ln717_3_fu_224_p4 = {{p_read1[11:4]}};

assign trunc_ln717_4_fu_358_p4 = {{p_read2[11:4]}};

assign trunc_ln717_5_fu_492_p4 = {{p_read3[11:4]}};

assign trunc_ln717_6_fu_626_p4 = {{p_read4[11:4]}};

assign trunc_ln727_2_fu_250_p1 = p_read1[2:0];

assign trunc_ln727_3_fu_384_p1 = p_read2[2:0];

assign trunc_ln727_4_fu_518_p1 = p_read3[2:0];

assign trunc_ln727_5_fu_652_p1 = p_read4[2:0];

assign trunc_ln727_fu_116_p1 = p_read[2:0];

assign zext_ln415_1_fu_280_p1 = and_ln412_2_fu_274_p2;

assign zext_ln415_2_fu_414_p1 = and_ln412_3_fu_408_p2;

assign zext_ln415_3_fu_548_p1 = and_ln412_4_fu_542_p2;

assign zext_ln415_4_fu_682_p1 = and_ln412_5_fu_676_p2;

assign zext_ln415_fu_146_p1 = and_ln412_fu_140_p2;

endmodule //myproject_relu_ap_fixed_16_4_5_3_0_ap_ufixed_8_0_4_0_0_relu_config4_s
